; =============================================================================
; OVERFLOW BANK $7E - relocated / custom monster sprite streams
; =============================================================================
; Generated by dwm/sprite_bank.py (cross-bank sprite allocator, GFX-2 backbone).
; EDITOR_DESIGN §8 reserved monster-sprite overflow region.
; Pointer table at $4001 (resolver reads $<bank>:$4001 + index*2); each entry
; targets an LZ stream below. Repoint a monster's gfx-ID (battle $00:$2B9F /
; follower $01:$49DF) to ($7E<<8 | index) to use one of these.
; =============================================================================

SECTION "Sprite Overflow Bank $7E", ROMX[$4000], BANK[$7E]
    db $7E                          ; bank self-ID at $4000 (resolver ignores)

SpriteOverflowPtrs_7E:                  ; pointer table @ $4001
    dw Follower_sp224           ; index 0 ($00)
    dw Battle_sp224             ; index 1 ($01)

Follower_sp224:  ; stream @ $4005 (259 B)
    db $00, $01, $05, $01, $01, $73, $72, $6b, $5a, $36, $2f, $77, $6d, $f8, $ef, $9f
    db $fb, $4f, $7f, $00, $00, $9c, $9c, $ac, $b4, $d8, $e8, $dc, $6c, $3e, $ee, $f2
    db $be, $e4, $fc, $84, $ff, $b7, $ff, $dc, $db, $1b, $1c, $e4, $ff, $ff, $8c, $74
    db $7b, $0f, $0f, $42, $fe, $da, $fe, $76, $b6, $a0, $60, $60, $a0, $c0, $40, $80
    db $80, $00, $00, $18, $18, $37, $2f, $1b, $16, $1f, $1b, $26, $3f, $42, $7f, $41
    db $7f, $20, $3f, $c0, $c0, $c0, $40, $c0, $40, $60, $e0, $e0, $a0, $17, $f7, $f9
    db $df, $76, $fe, $1c, $1f, $0b, $0f, $09, $0f, $09, $0f, $19, $1f, $73, $6e, $ef
    db $9f, $f0, $f0, $21, $ff, $e6, $fe, $f8, $38, $20, $e0, $c0, $40, $80, $80, $00
    db $00, $00, $00, $18, $18, $37, $2f, $1b, $16, $1f, $1b, $26, $3f, $42, $7f, $41
    db $7f, $e0, $ff, $c0, $c0, $c0, $40, $c0, $40, $60, $e0, $e0, $a0, $17, $f7, $f9
    db $df, $76, $fe, $fc, $bf, $eb, $af, $d9, $bf, $d9, $af, $79, $5f, $23, $3e, $1f
    db $1f, $00, $00, $21, $ff, $e6, $fe, $f8, $38, $20, $e0, $c0, $40, $80, $80, $00
    db $00, $00, $00, $00, $00, $39, $39, $35, $2d, $1b, $1f, $26, $3f, $43, $7e, $41
    db $7e, $27, $3c, $80, $80, $ce, $4e, $d6, $5a, $ec, $7c, $b2, $7e, $a1, $7f, $01
    db $ff, $12, $fe, $59, $7e, $5b, $7c, $69, $6e, $04, $07, $04, $07, $02, $03, $01
    db $01, $00, $00, $0d, $ff, $0d, $ff, $eb, $fb, $f0, $90, $ff, $4f, $7f, $e1, $9e
    db $fe, $60, $60
Battle_sp224:  ; stream @ $4108 (579 B)
    db $40, $02, $0d, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff
    db $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff
    db $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff
    db $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff
    db $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff
    db $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff
    db $00, $ff, $00, $ff, $00, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $18, $ff, $24
    db $f7, $13, $f3, $ff, $00, $00, $ff, $00, $ff, $00, $ff, $01, $ff, $01, $ff, $7f
    db $ff, $93, $93, $ff, $00, $01, $ff, $01, $ff, $02, $ff, $82, $ff, $44, $fd, $26
    db $7f, $18, $b8, $ff, $00, $00, $ff, $80, $ff, $80, $ff, $83, $ff, $85, $ff, $c9
    db $fd, $31, $3b, $ff, $00, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $fc
    db $ff, $93, $93, $ff, $00, $01, $fe, $01, $fe, $01, $fe, $01, $fe, $31, $fe, $49
    db $de, $91, $9e, $19, $f9, $24, $e4, $7c, $fc, $80, $c0, $f2, $f2, $4f, $cf, $b0
    db $ff, $c0, $ff, $49, $49, $81, $81, $71, $71, $09, $09, $45, $45, $f4, $fc, $0a
    db $fe, $01, $ff, $09, $c9, $16, $16, $25, $a7, $26, $66, $58, $d9, $95, $97, $16
    db $16, $08, $0a, $21, $27, $d1, $d1, $49, $cb, $c9, $cd, $35, $37, $52, $d2, $d0
    db $d0, $21, $a1, $25, $25, $06, $06, $1c, $1c, $20, $20, $4c, $4c, $5f, $7f, $a0
    db $ff, $00, $ff, $31, $3e, $49, $4e, $7d, $7e, $03, $06, $9f, $9e, $e5, $e6, $1b
    db $fe, $07, $fe, $00, $ff, $00, $ff, $0c, $ff, $0b, $ff, $08, $f9, $04, $fe, $02
    db $fe, $01, $ff, $01, $ff, $01, $ff, $01, $ff, $00, $ff, $e1, $ff, $1e, $5e, $00
    db $8c, $8d, $ad, $94, $95, $e3, $e3, $40, $58, $b0, $b4, $8f, $bf, $c0, $df, $b0
    db $b0, $cf, $df, $53, $53, $8f, $8f, $05, $35, $1b, $5b, $e3, $fb, $06, $f7, $1a
    db $1b, $e6, $f7, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00
    db $ff, $00, $ff, $01, $fe, $01, $fe, $01, $fe, $01, $fe, $01, $fe, $01, $fe, $01
    db $fe, $01, $fe, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $ff
    db $00, $ff, $00, $73, $f3, $10, $f0, $08, $f8, $07, $ff, $03, $ff, $00, $ff, $ff
    db $00, $ff, $00, $70, $77, $4f, $4f, $f0, $f1, $af, $af, $50, $50, $ff, $ff, $ff
    db $00, $ff, $00, $1c, $df, $e4, $f7, $18, $df, $f0, $ff, $60, $7f, $80, $ff, $ff
    db $00, $ff, $00, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $ff
    db $00, $ff, $00, $01, $fe, $01, $fe, $01, $fe, $01, $fe, $01, $fe, $01, $fe, $ff
    db $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff
    db $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff
    db $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff
    db $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff
    db $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff
    db $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff, $00, $ff
    db $00, $ff, $00

    ds 15541   ; zero-pad to $8000  (used 843 B of 16384)
