; =============================================================================
; bank_ext.asm — banks $80-$FF of the 4 MB ROM (S134, ROADMAP ARC CAP1)
; GENERATED by tools/build_project.py (editor2/core/emitters.py emit_bank_ext)
; from editor2/example-project — do not hand-edit.
; Every bank starts with its OWN NUMBER at $4000: rst $10, the audio bank swap
; and the text engine save the current bank by reading [$4000] (ARCHITECTURE
; "ROM banks $80-$FF (S133)"). A bank with compiler content is INCLUDEd; the
; rest are one-byte stubs (unused space, $00-filled by rgblink, the tail of
; bank $FF padded by rgbfix to 4 MB).
; =============================================================================
SECTION "ROM Bank $080", ROMX[$4000], BANK[$80]
    db $80                          ; bank self-ID at $4000
SECTION "ROM Bank $081", ROMX[$4000], BANK[$81]
    db $81                          ; bank self-ID at $4000
SECTION "ROM Bank $082", ROMX[$4000], BANK[$82]
    db $82                          ; bank self-ID at $4000
SECTION "ROM Bank $083", ROMX[$4000], BANK[$83]
    db $83                          ; bank self-ID at $4000
SECTION "ROM Bank $084", ROMX[$4000], BANK[$84]
    db $84                          ; bank self-ID at $4000
SECTION "ROM Bank $085", ROMX[$4000], BANK[$85]
    db $85                          ; bank self-ID at $4000
SECTION "ROM Bank $086", ROMX[$4000], BANK[$86]
    db $86                          ; bank self-ID at $4000
SECTION "ROM Bank $087", ROMX[$4000], BANK[$87]
    db $87                          ; bank self-ID at $4000
SECTION "ROM Bank $088", ROMX[$4000], BANK[$88]
    db $88                          ; bank self-ID at $4000
SECTION "ROM Bank $089", ROMX[$4000], BANK[$89]
    db $89                          ; bank self-ID at $4000
SECTION "ROM Bank $08A", ROMX[$4000], BANK[$8A]
    db $8A                          ; bank self-ID at $4000
SECTION "ROM Bank $08B", ROMX[$4000], BANK[$8B]
    db $8B                          ; bank self-ID at $4000
SECTION "ROM Bank $08C", ROMX[$4000], BANK[$8C]
    db $8C                          ; bank self-ID at $4000
SECTION "ROM Bank $08D", ROMX[$4000], BANK[$8D]
    db $8D                          ; bank self-ID at $4000
SECTION "ROM Bank $08E", ROMX[$4000], BANK[$8E]
    db $8E                          ; bank self-ID at $4000
SECTION "ROM Bank $08F", ROMX[$4000], BANK[$8F]
    db $8F                          ; bank self-ID at $4000
SECTION "ROM Bank $090", ROMX[$4000], BANK[$90]
    db $90                          ; bank self-ID at $4000
SECTION "ROM Bank $091", ROMX[$4000], BANK[$91]
    db $91                          ; bank self-ID at $4000
SECTION "ROM Bank $092", ROMX[$4000], BANK[$92]
    db $92                          ; bank self-ID at $4000
SECTION "ROM Bank $093", ROMX[$4000], BANK[$93]
    db $93                          ; bank self-ID at $4000
SECTION "ROM Bank $094", ROMX[$4000], BANK[$94]
    db $94                          ; bank self-ID at $4000
SECTION "ROM Bank $095", ROMX[$4000], BANK[$95]
    db $95                          ; bank self-ID at $4000
SECTION "ROM Bank $096", ROMX[$4000], BANK[$96]
    db $96                          ; bank self-ID at $4000
SECTION "ROM Bank $097", ROMX[$4000], BANK[$97]
    db $97                          ; bank self-ID at $4000
SECTION "ROM Bank $098", ROMX[$4000], BANK[$98]
    db $98                          ; bank self-ID at $4000
SECTION "ROM Bank $099", ROMX[$4000], BANK[$99]
    db $99                          ; bank self-ID at $4000
SECTION "ROM Bank $09A", ROMX[$4000], BANK[$9A]
    db $9A                          ; bank self-ID at $4000
SECTION "ROM Bank $09B", ROMX[$4000], BANK[$9B]
    db $9B                          ; bank self-ID at $4000
SECTION "ROM Bank $09C", ROMX[$4000], BANK[$9C]
    db $9C                          ; bank self-ID at $4000
SECTION "ROM Bank $09D", ROMX[$4000], BANK[$9D]
    db $9D                          ; bank self-ID at $4000
SECTION "ROM Bank $09E", ROMX[$4000], BANK[$9E]
    db $9E                          ; bank self-ID at $4000
SECTION "ROM Bank $09F", ROMX[$4000], BANK[$9F]
    db $9F                          ; bank self-ID at $4000
SECTION "ROM Bank $0A0", ROMX[$4000], BANK[$A0]
    db $A0                          ; bank self-ID at $4000
SECTION "ROM Bank $0A1", ROMX[$4000], BANK[$A1]
    db $A1                          ; bank self-ID at $4000
SECTION "ROM Bank $0A2", ROMX[$4000], BANK[$A2]
    db $A2                          ; bank self-ID at $4000
SECTION "ROM Bank $0A3", ROMX[$4000], BANK[$A3]
    db $A3                          ; bank self-ID at $4000
SECTION "ROM Bank $0A4", ROMX[$4000], BANK[$A4]
    db $A4                          ; bank self-ID at $4000
SECTION "ROM Bank $0A5", ROMX[$4000], BANK[$A5]
    db $A5                          ; bank self-ID at $4000
SECTION "ROM Bank $0A6", ROMX[$4000], BANK[$A6]
    db $A6                          ; bank self-ID at $4000
SECTION "ROM Bank $0A7", ROMX[$4000], BANK[$A7]
    db $A7                          ; bank self-ID at $4000
SECTION "ROM Bank $0A8", ROMX[$4000], BANK[$A8]
    db $A8                          ; bank self-ID at $4000
SECTION "ROM Bank $0A9", ROMX[$4000], BANK[$A9]
    db $A9                          ; bank self-ID at $4000
SECTION "ROM Bank $0AA", ROMX[$4000], BANK[$AA]
    db $AA                          ; bank self-ID at $4000
SECTION "ROM Bank $0AB", ROMX[$4000], BANK[$AB]
    db $AB                          ; bank self-ID at $4000
SECTION "ROM Bank $0AC", ROMX[$4000], BANK[$AC]
    db $AC                          ; bank self-ID at $4000
SECTION "ROM Bank $0AD", ROMX[$4000], BANK[$AD]
    db $AD                          ; bank self-ID at $4000
SECTION "ROM Bank $0AE", ROMX[$4000], BANK[$AE]
    db $AE                          ; bank self-ID at $4000
SECTION "ROM Bank $0AF", ROMX[$4000], BANK[$AF]
    db $AF                          ; bank self-ID at $4000
SECTION "ROM Bank $0B0", ROMX[$4000], BANK[$B0]
    db $B0                          ; bank self-ID at $4000
SECTION "ROM Bank $0B1", ROMX[$4000], BANK[$B1]
    db $B1                          ; bank self-ID at $4000
SECTION "ROM Bank $0B2", ROMX[$4000], BANK[$B2]
    db $B2                          ; bank self-ID at $4000
SECTION "ROM Bank $0B3", ROMX[$4000], BANK[$B3]
    db $B3                          ; bank self-ID at $4000
SECTION "ROM Bank $0B4", ROMX[$4000], BANK[$B4]
    db $B4                          ; bank self-ID at $4000
SECTION "ROM Bank $0B5", ROMX[$4000], BANK[$B5]
    db $B5                          ; bank self-ID at $4000
SECTION "ROM Bank $0B6", ROMX[$4000], BANK[$B6]
    db $B6                          ; bank self-ID at $4000
SECTION "ROM Bank $0B7", ROMX[$4000], BANK[$B7]
    db $B7                          ; bank self-ID at $4000
SECTION "ROM Bank $0B8", ROMX[$4000], BANK[$B8]
    db $B8                          ; bank self-ID at $4000
SECTION "ROM Bank $0B9", ROMX[$4000], BANK[$B9]
    db $B9                          ; bank self-ID at $4000
SECTION "ROM Bank $0BA", ROMX[$4000], BANK[$BA]
    db $BA                          ; bank self-ID at $4000
SECTION "ROM Bank $0BB", ROMX[$4000], BANK[$BB]
    db $BB                          ; bank self-ID at $4000
SECTION "ROM Bank $0BC", ROMX[$4000], BANK[$BC]
    db $BC                          ; bank self-ID at $4000
SECTION "ROM Bank $0BD", ROMX[$4000], BANK[$BD]
    db $BD                          ; bank self-ID at $4000
SECTION "ROM Bank $0BE", ROMX[$4000], BANK[$BE]
    db $BE                          ; bank self-ID at $4000
SECTION "ROM Bank $0BF", ROMX[$4000], BANK[$BF]
    db $BF                          ; bank self-ID at $4000
SECTION "ROM Bank $0C0", ROMX[$4000], BANK[$C0]
    db $C0                          ; bank self-ID at $4000
SECTION "ROM Bank $0C1", ROMX[$4000], BANK[$C1]
    db $C1                          ; bank self-ID at $4000
SECTION "ROM Bank $0C2", ROMX[$4000], BANK[$C2]
    db $C2                          ; bank self-ID at $4000
SECTION "ROM Bank $0C3", ROMX[$4000], BANK[$C3]
    db $C3                          ; bank self-ID at $4000
SECTION "ROM Bank $0C4", ROMX[$4000], BANK[$C4]
    db $C4                          ; bank self-ID at $4000
SECTION "ROM Bank $0C5", ROMX[$4000], BANK[$C5]
    db $C5                          ; bank self-ID at $4000
SECTION "ROM Bank $0C6", ROMX[$4000], BANK[$C6]
    db $C6                          ; bank self-ID at $4000
SECTION "ROM Bank $0C7", ROMX[$4000], BANK[$C7]
    db $C7                          ; bank self-ID at $4000
SECTION "ROM Bank $0C8", ROMX[$4000], BANK[$C8]
    db $C8                          ; bank self-ID at $4000
SECTION "ROM Bank $0C9", ROMX[$4000], BANK[$C9]
    db $C9                          ; bank self-ID at $4000
SECTION "ROM Bank $0CA", ROMX[$4000], BANK[$CA]
    db $CA                          ; bank self-ID at $4000
SECTION "ROM Bank $0CB", ROMX[$4000], BANK[$CB]
    db $CB                          ; bank self-ID at $4000
SECTION "ROM Bank $0CC", ROMX[$4000], BANK[$CC]
    db $CC                          ; bank self-ID at $4000
SECTION "ROM Bank $0CD", ROMX[$4000], BANK[$CD]
    db $CD                          ; bank self-ID at $4000
SECTION "ROM Bank $0CE", ROMX[$4000], BANK[$CE]
    db $CE                          ; bank self-ID at $4000
SECTION "ROM Bank $0CF", ROMX[$4000], BANK[$CF]
    db $CF                          ; bank self-ID at $4000
SECTION "ROM Bank $0D0", ROMX[$4000], BANK[$D0]
    db $D0                          ; bank self-ID at $4000
SECTION "ROM Bank $0D1", ROMX[$4000], BANK[$D1]
    db $D1                          ; bank self-ID at $4000
SECTION "ROM Bank $0D2", ROMX[$4000], BANK[$D2]
    db $D2                          ; bank self-ID at $4000
SECTION "ROM Bank $0D3", ROMX[$4000], BANK[$D3]
    db $D3                          ; bank self-ID at $4000
SECTION "ROM Bank $0D4", ROMX[$4000], BANK[$D4]
    db $D4                          ; bank self-ID at $4000
SECTION "ROM Bank $0D5", ROMX[$4000], BANK[$D5]
    db $D5                          ; bank self-ID at $4000
SECTION "ROM Bank $0D6", ROMX[$4000], BANK[$D6]
    db $D6                          ; bank self-ID at $4000
SECTION "ROM Bank $0D7", ROMX[$4000], BANK[$D7]
    db $D7                          ; bank self-ID at $4000
SECTION "ROM Bank $0D8", ROMX[$4000], BANK[$D8]
    db $D8                          ; bank self-ID at $4000
SECTION "ROM Bank $0D9", ROMX[$4000], BANK[$D9]
    db $D9                          ; bank self-ID at $4000
SECTION "ROM Bank $0DA", ROMX[$4000], BANK[$DA]
    db $DA                          ; bank self-ID at $4000
SECTION "ROM Bank $0DB", ROMX[$4000], BANK[$DB]
    db $DB                          ; bank self-ID at $4000
SECTION "ROM Bank $0DC", ROMX[$4000], BANK[$DC]
    db $DC                          ; bank self-ID at $4000
SECTION "ROM Bank $0DD", ROMX[$4000], BANK[$DD]
    db $DD                          ; bank self-ID at $4000
SECTION "ROM Bank $0DE", ROMX[$4000], BANK[$DE]
    db $DE                          ; bank self-ID at $4000
SECTION "ROM Bank $0DF", ROMX[$4000], BANK[$DF]
    db $DF                          ; bank self-ID at $4000
SECTION "ROM Bank $0E0", ROMX[$4000], BANK[$E0]
    db $E0                          ; bank self-ID at $4000
SECTION "ROM Bank $0E1", ROMX[$4000], BANK[$E1]
    db $E1                          ; bank self-ID at $4000
SECTION "ROM Bank $0E2", ROMX[$4000], BANK[$E2]
    db $E2                          ; bank self-ID at $4000
SECTION "ROM Bank $0E3", ROMX[$4000], BANK[$E3]
    db $E3                          ; bank self-ID at $4000
SECTION "ROM Bank $0E4", ROMX[$4000], BANK[$E4]
    db $E4                          ; bank self-ID at $4000
SECTION "ROM Bank $0E5", ROMX[$4000], BANK[$E5]
    db $E5                          ; bank self-ID at $4000
SECTION "ROM Bank $0E6", ROMX[$4000], BANK[$E6]
    db $E6                          ; bank self-ID at $4000
SECTION "ROM Bank $0E7", ROMX[$4000], BANK[$E7]
    db $E7                          ; bank self-ID at $4000
SECTION "ROM Bank $0E8", ROMX[$4000], BANK[$E8]
    db $E8                          ; bank self-ID at $4000
SECTION "ROM Bank $0E9", ROMX[$4000], BANK[$E9]
    db $E9                          ; bank self-ID at $4000
SECTION "ROM Bank $0EA", ROMX[$4000], BANK[$EA]
    db $EA                          ; bank self-ID at $4000
SECTION "ROM Bank $0EB", ROMX[$4000], BANK[$EB]
    db $EB                          ; bank self-ID at $4000
SECTION "ROM Bank $0EC", ROMX[$4000], BANK[$EC]
    db $EC                          ; bank self-ID at $4000
SECTION "ROM Bank $0ED", ROMX[$4000], BANK[$ED]
    db $ED                          ; bank self-ID at $4000
SECTION "ROM Bank $0EE", ROMX[$4000], BANK[$EE]
    db $EE                          ; bank self-ID at $4000
SECTION "ROM Bank $0EF", ROMX[$4000], BANK[$EF]
    db $EF                          ; bank self-ID at $4000
SECTION "ROM Bank $0F0", ROMX[$4000], BANK[$F0]
    db $F0                          ; bank self-ID at $4000
SECTION "ROM Bank $0F1", ROMX[$4000], BANK[$F1]
    db $F1                          ; bank self-ID at $4000
SECTION "ROM Bank $0F2", ROMX[$4000], BANK[$F2]
    db $F2                          ; bank self-ID at $4000
SECTION "ROM Bank $0F3", ROMX[$4000], BANK[$F3]
    db $F3                          ; bank self-ID at $4000
SECTION "ROM Bank $0F4", ROMX[$4000], BANK[$F4]
    db $F4                          ; bank self-ID at $4000
SECTION "ROM Bank $0F5", ROMX[$4000], BANK[$F5]
    db $F5                          ; bank self-ID at $4000
SECTION "ROM Bank $0F6", ROMX[$4000], BANK[$F6]
    db $F6                          ; bank self-ID at $4000
SECTION "ROM Bank $0F7", ROMX[$4000], BANK[$F7]
    db $F7                          ; bank self-ID at $4000
SECTION "ROM Bank $0F8", ROMX[$4000], BANK[$F8]
    db $F8                          ; bank self-ID at $4000
SECTION "ROM Bank $0F9", ROMX[$4000], BANK[$F9]
    db $F9                          ; bank self-ID at $4000
SECTION "ROM Bank $0FA", ROMX[$4000], BANK[$FA]
    db $FA                          ; bank self-ID at $4000
SECTION "ROM Bank $0FB", ROMX[$4000], BANK[$FB]
    db $FB                          ; bank self-ID at $4000
SECTION "ROM Bank $0FC", ROMX[$4000], BANK[$FC]
    db $FC                          ; bank self-ID at $4000
SECTION "ROM Bank $0FD", ROMX[$4000], BANK[$FD]
    db $FD                          ; bank self-ID at $4000
SECTION "ROM Bank $0FE", ROMX[$4000], BANK[$FE]
    db $FE                          ; bank self-ID at $4000
SECTION "ROM Bank $0FF", ROMX[$4000], BANK[$FF]
    db $FF                          ; bank self-ID at $4000
