; =============================================================================
; BANK $64 — Custom Tile Layout + Attribute Data
; =============================================================================
; Layout generated by tools/build_combined_tileset.py
; Attr data generated by tools/build_combined_tileset.py
; Format: pointer table at $4001, LZSS compressed data
; Entry 0: tile layout (512 bytes decompressed, 32×16 padded grid)
; Entry 1: palette attributes (256 bytes decompressed, nibble-packed)
; Engine reads via DecompressTileLayout ($1627): D=bank, E=entry index
; =============================================================================

SECTION "ROM Bank $064", ROMX[$4000], BANK[$64]
    db $64  ; bank self-ID

; Pointer table at $4001 — indexed by entry number (E register)
; Entry 0: tile layout data (used by room step entry byte 0)
; Entry 1: palette attribute data (used by bank $17 CustomAttrCheck)
    dw CustomLayout_Room6B
    dw CustomAttr_Room6B

; CustomLayout_Room6B: 217 bytes compressed (512 decompressed)
CustomLayout_Room6B:
    db $00, $02, $00, $15, $16, $15, $16, $46, $47, $00, $02, $00, $00, $00, $00, $00
    db $00, $00, $24, $25, $FF, $FF, $FF, $FF, $00, $14, $00, $00, $14, $00, $17, $18
    db $17, $18, $44, $45, $00, $22, $00, $00, $20, $00, $00, $20, $00, $26, $27, $00
    db $14, $08, $15, $16, $4A, $4B, $42, $43, $2C, $2D, $42, $43, $4A, $4B, $2A, $2B
    db $48, $49, $00, $10, $0E, $1E, $1F, $1A, $1B, $2E, $2F, $1A, $1B, $1E, $1F, $28
    db $29, $1C, $1D, $00, $30, $0E, $38, $39, $38, $39, $00, $82, $00, $00, $82, $00
    db $4C, $4F, $00, $10, $0E, $3A, $3B, $3A, $3B, $00, $A2, $00, $00, $A2, $00, $50
    db $51, $00, $70, $0F, $01, $34, $35, $00, $82, $00, $39, $39, $38, $39, $20, $21
    db $00, $90, $0F, $01, $36, $37, $00, $A2, $00, $3B, $3B, $3A, $3B, $22, $23, $00
    db $70, $0F, $01, $0E, $0F, $00, $82, $06, $00, $90, $0F, $01, $10, $11, $00, $A2
    db $06, $00, $70, $0F, $01, $00, $C7, $00, $00, $08, $1F, $09, $00, $E7, $00, $00
    db $28, $1F, $09, $00, $82, $08, $00, $90, $0F, $0B, $00, $2E, $1E, $19, $19, $19
    db $19, $19, $19, $30, $31, $00, $0A, $04, $00, $10, $0C, $40, $41, $40, $41, $40
    db $41, $32, $33, $00, $2A, $04, $00, $30, $0C

; CustomAttr_Room6B: 85 bytes compressed (256 decompressed)
CustomAttr_Room6B:
    db $00, $01, $01, $00, $00, $33, $00, $33, $00, $00, $00, $00, $11, $01, $05, $00
    db $01, $05, $00, $01, $02, $0B, $44, $33, $77, $33, $44, $55, $01, $17, $07, $00
    db $22, $00, $01, $25, $08, $01, $0A, $02, $66, $01, $38, $0C, $01, $08, $06, $22
    db $01, $2D, $02, $01, $59, $0C, $01, $59, $0A, $01, $07, $07, $01, $82, $0C, $01
    db $0A, $03, $01, $99, $0C, $01, $99, $0F, $0D, $01, $39, $06, $01, $82, $02, $01
    db $D9, $0C, $01, $09, $03

; Remaining bank space available for additional layouts/attrs
