; =============================================================================
; BANK $6E — ARENA SYSTEMS (S109, ROADMAP P3.10b; hand-authored,
; patches/bank_06e.asm)
; =============================================================================
; The arena's three-monster teams are FORMULA-addressed enemy-stats rows
; (SIDEQUEST_MAP "Arena / gate-boss ROSTER format"): ArenaBattleSetup (script
; opcode $1F, bank $04) and its between-matches clone LoadArenaEnemyStats
; (bank $50) load EID = $E0 + 9*wArenaGroup + 3*wColiseumBattle + slot into
; the three battle slots, write $DA02 = 2 (3 enemies) and fill the Arena Battle
; room's display list $D7CA-$D7D1 ([draw id, is_monster] x 4: entry 0 = the
; master, entry 2 = slot 0 (the middle monster), entry 1 = slot 1, entry 3 =
; slot 2 — the room's NPCs $F0-$F3 draw them, bank $0B Call_00b_4839).
;
; entry 0  ArenaTeamFixup — far-called from the LAST instruction pair of both
;          routines (`ld a,$01 / ld [$d7d1],a / ret` became `ld hl,$6E00 /
;          rst $10 / ret / nop`, same size; banks $04 and $50 admit no inserts).
;          It writes $D7D1 = 1 (the pair it replaced), then applies the match's
;          TEAM SIZE from ArenaTeamSizeTable (compiler region gd_arena_team_sizes,
;          gamedata.arena.<group>.matches.<m>.size):
;            size 3 (vanilla, and every row of an unedited project) -> nothing
;            size 2 -> $DA02 = 1 (slots 0-1 fight), display entry 3 = [$FF, $00]
;            size 1 -> $DA02 = 0 (slot 0 fights), entries 1 and 3 = [$FF, $00]
;          A display entry whose draw id is $FF gives its NPC sprite $FF = not
;          drawn (Call_00b_4839's own $FF path, the one vanilla SetBtl_67ae
;          uses for the coliseum). The battle itself takes 1-3 enemies from
;          $DA02 like any field battle (PyBoy S109, the user's save: 1- and
;          2-monster arena teams fought, won, the next match loaded).
;          Index = 3*wArenaGroup + wColiseumBattle: ArenaBattleSetup runs with
;          wColiseumBattle = 0 (the lobby script writes it), the bank-$50 clone
;          after each won match with wColiseumBattle = the NEXT match (the Arena
;          Battle room script counts it up before cmd_20); the clone returns
;          early at 3, so it never asks for a fourth. King (group 9, the code
;          overrides its EIDs with $01E1-$01E3) = index 27. An index >= 30
;          (never written by the game) leaves the vanilla values.
; rst $10 contract (bank $00): A/F/BC clobbered; both callers `ret` at once.
; =============================================================================

SECTION "ROM Bank $06E", ROMX[$4000], BANK[$6E]

    db $6E                              ; bank self-ID at $4000

; rst-$10 entry table at $4001
    dw ArenaTeamFixup                   ; entry 0  (HL=$6E00)

ARENA_TEAM_ROWS EQU 30                  ; 10 groups x 3 matches

ArenaTeamFixup:
    ld a, $01
    ld [$d7d1], a                       ; display entry 3 = monster (the replaced pair)
    ld a, [wArenaGroup]
    ld b, a
    add a
    add b                               ; 3 * group
    ld b, a
    ld a, [wColiseumBattle]
    add b                               ; + match
    cp ARENA_TEAM_ROWS
    ret nc
    ld hl, ArenaTeamSizeTable
    add l
    ld l, a
    ld a, $00
    adc h
    ld h, a
    ld a, [hl]                          ; team size 1-3
    cp $03
    ret nc                              ; 3 = the vanilla team
    or a
    ret z                               ; (0 is never emitted)
    dec a
    ld [$da02], a                       ; enemy count - 1
    ld hl, $d7d0                        ; slot 2 (display entry 3) leaves
    ld [hl], $ff
    inc hl
    ld [hl], $00
    or a
    ret nz                              ; size 2
    ld hl, $d7cc                        ; size 1: slot 1 (display entry 1) too
    ld [hl], $ff
    inc hl
    ld [hl], $00
    ret

; @BUILD_PROJECT BEGIN gd_arena_team_sizes
; (generated by editor2 `gd_arena_team_sizes` from gamedata.arena)
ArenaTeamSizeTable:  ; index 3*group + match; 1-3 monsters
    db 3, 3, 3   ; G class
    db 3, 3, 3   ; F class
    db 3, 3, 3   ; E class
    db 3, 3, 3   ; D class
    db 3, 3, 3   ; C class
    db 3, 3, 3   ; B class
    db 3, 3, 3   ; A class
    db 3, 3, 3   ; S class
    db 3, 3, 3   ; Starry Night
    db 3, 3, 3   ; King (only match 1 is fought)
; @BUILD_PROJECT END gd_arena_team_sizes

    ds $8000 - @, $00
