; =============================================================================
; OVERFLOW BANK $7E - relocated / custom monster sprite streams
; =============================================================================
; Generated by dwm/sprite_bank.py (cross-bank sprite allocator, GFX-2 backbone).
; EDITOR_DESIGN §8 reserved monster-sprite overflow region.
; Pointer table at $4001 (resolver reads $<bank>:$4001 + index*2); each entry
; targets an LZ stream below. Repoint a monster's gfx-ID (battle $00:$2B9F /
; follower $01:$49DF) to ($7E<<8 | index) to use one of these.
; =============================================================================

SECTION "Sprite Overflow Bank $7E", ROMX[$4000], BANK[$7E]
    db $7E                          ; bank self-ID at $4000 (resolver ignores)

SpriteOverflowPtrs_7E:                  ; pointer table @ $4001
    dw Follower_sp224           ; index 0 ($00)

Follower_sp224:  ; stream @ $4003 (259 B)
    db $00, $01, $05, $01, $01, $73, $72, $6b, $5a, $36, $2f, $77, $6d, $f8, $ef, $9f
    db $fb, $4f, $7f, $00, $00, $9c, $9c, $ac, $b4, $d8, $e8, $dc, $6c, $3e, $ee, $f2
    db $be, $e4, $fc, $84, $ff, $b7, $ff, $dc, $db, $1b, $1c, $e4, $ff, $ff, $8c, $74
    db $7b, $0f, $0f, $42, $fe, $da, $fe, $76, $b6, $a0, $60, $60, $a0, $c0, $40, $80
    db $80, $00, $00, $18, $18, $37, $2f, $1b, $16, $1f, $1b, $26, $3f, $42, $7f, $41
    db $7f, $20, $3f, $c0, $c0, $c0, $40, $c0, $40, $60, $e0, $e0, $a0, $17, $f7, $f9
    db $df, $76, $fe, $1c, $1f, $0b, $0f, $09, $0f, $09, $0f, $19, $1f, $73, $6e, $ef
    db $9f, $f0, $f0, $21, $ff, $e6, $fe, $f8, $38, $20, $e0, $c0, $40, $80, $80, $00
    db $00, $00, $00, $18, $18, $37, $2f, $1b, $16, $1f, $1b, $26, $3f, $42, $7f, $41
    db $7f, $e0, $ff, $c0, $c0, $c0, $40, $c0, $40, $60, $e0, $e0, $a0, $17, $f7, $f9
    db $df, $76, $fe, $fc, $bf, $eb, $af, $d9, $bf, $d9, $af, $79, $5f, $23, $3e, $1f
    db $1f, $00, $00, $21, $ff, $e6, $fe, $f8, $38, $20, $e0, $c0, $40, $80, $80, $00
    db $00, $00, $00, $00, $00, $39, $39, $35, $2d, $1b, $1f, $26, $3f, $43, $7e, $41
    db $7e, $27, $3c, $80, $80, $ce, $4e, $d6, $5a, $ec, $7c, $b2, $7e, $a1, $7f, $01
    db $ff, $12, $fe, $59, $7e, $5b, $7c, $69, $6e, $04, $07, $04, $07, $02, $03, $01
    db $01, $00, $00, $0d, $ff, $0d, $ff, $eb, $fb, $f0, $90, $ff, $4f, $7f, $e1, $9e
    db $fe, $60, $60

    ds 16122   ; zero-pad to $8000  (used 262 B of 16384)
