; =============================================================================
; BANK $6A - NEW SPECIES DATA (Phase N, ids 224..255)
; =============================================================================
; Generated by tools/build_new_species.py (source: extracted/new_species.json)
;
; Reached from the bank $03 info-loader fork via `ld hl,$6a00; rst $10`
; (entry 0). The far-copy routine runs IN this bank (so the high table at
; $4000-$7FFF is mapped), reads $DA31 (species id >= 224), and copies the
; 43-byte info entry for (id-224) into DE (= $DA33, preserved across rst $10).
; Mul8x8To16 lives in ROM0 so it is callable here without a bank switch.
; =============================================================================

SECTION "ROM Bank $06A", ROMX[$4000], BANK[$6A]
    db $6A                            ; bank self-ID at $4000

; rst-$10 entry table at $4001 (HL=$6a00 dispatches entry 0)
    dw NewSpeciesInfoCopy

; -----------------------------------------------------------------------------
; NewSpeciesInfoCopy - copy a new-species 43-byte info entry to DE (=$DA33).
; In: $DA31 = species id (>=224), DE = dest. Mirrors the vanilla copy loop.
; -----------------------------------------------------------------------------
NewSpeciesInfoCopy:
    ld a, [wTempSpeciesId]            ; $DA31 = species id (>=224)
    sub $e0                           ; index = id - 224
    ld c, $2b                         ; 43 = entry size
    call Mul8x8To16                   ; HL = index * 43
    ld bc, NewSpeciesHighInfoTable    ; + high table base (this bank)
    add hl, bc
    ld b, $2b                         ; copy 43 bytes
.copy:
    ld a, [hl+]
    ld [de], a
    inc de
    dec b
    jr nz, .copy
    ret

; -----------------------------------------------------------------------------
; NewSpeciesHighInfoTable - 32 slots x 43 bytes, indexed (species_id - 224).
; Unpopulated slots are zero-filled (no species defined there yet).
; -----------------------------------------------------------------------------
NewSpeciesHighInfoTable:
; --- slot 0: species 224 (cloned from species 78) ---
    db $00, $28, $02, $02, $01, $00, $15, $1a, $33, $0b, $04, $08, $0d, $11, $0b, $00, $00, $00, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $02, $02, $02, $02, $02, $00, $00
; --- slot 1: species 225 (empty) ---
    ds 43, $00
; --- slot 2: species 226 (empty) ---
    ds 43, $00
; --- slot 3: species 227 (empty) ---
    ds 43, $00
; --- slot 4: species 228 (empty) ---
    ds 43, $00
; --- slot 5: species 229 (empty) ---
    ds 43, $00
; --- slot 6: species 230 (empty) ---
    ds 43, $00
; --- slot 7: species 231 (empty) ---
    ds 43, $00
; --- slot 8: species 232 (empty) ---
    ds 43, $00
; --- slot 9: species 233 (empty) ---
    ds 43, $00
; --- slot 10: species 234 (empty) ---
    ds 43, $00
; --- slot 11: species 235 (empty) ---
    ds 43, $00
; --- slot 12: species 236 (empty) ---
    ds 43, $00
; --- slot 13: species 237 (empty) ---
    ds 43, $00
; --- slot 14: species 238 (empty) ---
    ds 43, $00
; --- slot 15: species 239 (empty) ---
    ds 43, $00
; --- slot 16: species 240 (empty) ---
    ds 43, $00
; --- slot 17: species 241 (empty) ---
    ds 43, $00
; --- slot 18: species 242 (empty) ---
    ds 43, $00
; --- slot 19: species 243 (empty) ---
    ds 43, $00
; --- slot 20: species 244 (empty) ---
    ds 43, $00
; --- slot 21: species 245 (empty) ---
    ds 43, $00
; --- slot 22: species 246 (empty) ---
    ds 43, $00
; --- slot 23: species 247 (empty) ---
    ds 43, $00
; --- slot 24: species 248 (empty) ---
    ds 43, $00
; --- slot 25: species 249 (empty) ---
    ds 43, $00
; --- slot 26: species 250 (empty) ---
    ds 43, $00
; --- slot 27: species 251 (empty) ---
    ds 43, $00
; --- slot 28: species 252 (empty) ---
    ds 43, $00
; --- slot 29: species 253 (empty) ---
    ds 43, $00
; --- slot 30: species 254 (empty) ---
    ds 43, $00
; --- slot 31: species 255 (empty) ---
    ds 43, $00

