; =============================================================================
; BANK $64 — Custom Tile Layout + Attribute Data
; =============================================================================
; Layout generated by tools/build_combined_tileset.py
; Attr data generated by tools/build_combined_tileset.py
; Format: pointer table at $4001, LZSS compressed data
; Entry 0: tile layout (512 bytes decompressed, 32×16 padded grid)
; Entry 1: palette attributes (256 bytes decompressed, nibble-packed)
; Engine reads via DecompressTileLayout ($1627): D=bank, E=entry index
; =============================================================================

SECTION "ROM Bank $064", ROMX[$4000], BANK[$64]
    db $64  ; bank self-ID

; Pointer table at $4001 — indexed by entry number (E register)
; Entry 0: tile layout data (used by room step entry byte 0)
; Entry 1: palette attribute data (used by bank $17 CustomAttrCheck)
    dw CustomLayout_Room6B
    dw CustomAttr_Room6B

; CustomLayout_Room6B: 264 bytes compressed (512 decompressed)
CustomLayout_Room6B:
    db $00, $02, $00, $3B, $3C, $5D, $5E, $5D, $5E, $00, $02, $00, $00, $02, $02, $15
    db $15, $15, $15, $FF, $FF, $FF, $FF, $00, $14, $00, $00, $14, $00, $3D, $3E, $23
    db $24, $29, $60, $5F, $60, $5F, $00, $25, $00, $60, $5F, $60, $16, $16, $16, $16
    db $00, $14, $08, $3B, $3C, $22, $25, $28, $5A, $4D, $4E, $3F, $40, $59, $5A, $59
    db $5A, $3B, $3C, $17, $17, $17, $17, $00, $14, $0A, $21, $26, $27, $5C, $4F, $50
    db $41, $42, $5B, $5C, $5B, $5C, $3D, $3E, $18, $18, $18, $18, $00, $34, $0A, $37
    db $38, $37, $38, $00, $82, $00, $1D, $1E, $43, $44, $3B, $3C, $19, $19, $19, $19
    db $00, $14, $0A, $39, $3A, $39, $3A, $00, $A2, $00, $1F, $20, $46, $45, $3D, $3E
    db $1A, $1A, $1A, $1A, $00, $74, $0F, $03, $61, $62, $47, $48, $3B, $3C, $00, $B0
    db $0C, $00, $A0, $02, $68, $69, $6A, $00, $A3, $01, $00, $AE, $0F, $03, $0E, $0F
    db $6B, $6C, $6D, $00, $83, $01, $00, $CE, $0F, $03, $10, $11, $6B, $6C, $6D, $00
    db $E9, $0F, $08, $33, $34, $6E, $6F, $70, $38, $37, $38, $51, $52, $00, $CE, $0F
    db $03, $35, $36, $00, $A2, $02, $53, $54, $00, $AE, $0E, $55, $56, $00, $82, $04
    db $37, $38, $49, $4A, $00, $CE, $0E, $57, $58, $00, $A2, $04, $39, $3A, $4B, $4C
    db $3D, $3E, $1B, $1B, $1C, $1C, $00, $74, $1A, $3B, $3C, $00, $80, $00, $00, $C2
    db $10, $00, $C2, $10, $00, $B0, $1C, $57, $58, $3D, $3E, $00, $A0, $00, $00, $E2
    db $10, $00, $E2, $10, $2A, $00, $B1, $1B

; CustomAttr_Room6B: 73 bytes compressed (256 decompressed)
CustomAttr_Room6B:
    db $00, $01, $01, $00, $00, $00, $00, $01, $00, $00, $11, $11, $01, $00, $03, $55
    db $50, $01, $03, $0C, $01, $03, $0F, $0B, $01, $00, $00, $77, $44, $01, $37, $0C
    db $01, $37, $0F, $09, $22, $20, $01, $35, $09, $66, $01, $73, $0C, $01, $73, $0F
    db $0D, $01, $33, $0E, $00, $01, $46, $0B, $00, $44, $00, $33, $33, $01, $BA, $08
    db $00, $01, $D7, $0C, $00, $03, $01, $D9, $03

; Remaining bank space available for additional layouts/attrs
