; =============================================================================
; BANK $64 — Custom Tile Layout + Attribute Data
; =============================================================================
; Layout generated by tools/tile_layout_compiler.py
; Attr data generated by tools/generate_attr_map.py
; Format: pointer table at $4001, LZSS compressed data
; Entry 0: tile layout (512 bytes decompressed, 32×16 padded grid)
; Entry 1: palette attributes (256 bytes decompressed, nibble-packed)
; Engine reads via DecompressTileLayout ($1627): D=bank, E=entry index
; =============================================================================

SECTION "ROM Bank $064", ROMX[$4000], BANK[$64]
    db $64  ; bank self-ID

; Pointer table at $4001 — indexed by entry number (E register)
; Entry 0: tile layout data (used by room step entry byte 0)
; Entry 1: palette attribute data (used by bank $17 CustomAttrCheck)
    dw CustomLayout_Room6B
    dw CustomAttr_Room6B

; CustomLayout_Room6B: 238 bytes compressed (512 decompressed)
; Source: extracted/custom_layouts/room_6b_medalman.json
; Tileset: 30:12 (MedalMan, mapID $16)
CustomLayout_Room6B:
    db $00, $02, $0C, $11, $10, $04, $05, $06, $07, $04, $05, $04, $04, $04, $04, $0C
    db $08, $00, $04, $04, $04, $10, $FF, $FF, $FF, $FF, $0C, $14, $00, $0C, $14, $00
    db $11, $08, $40, $41, $40, $00, $00, $01, $00, $01, $0C, $26, $00, $0C, $26, $01
    db $09, $0C, $14, $09, $09, $42, $43, $40, $00, $50, $51, $0C, $26, $02, $02, $03
    db $02, $03, $0C, $32, $0B, $0A, $42, $43, $42, $00, $52, $53, $0C, $4E, $00, $02
    db $03, $0C, $2E, $0F, $00, $0B, $40, $41, $40, $41, $0C, $82, $00, $0C, $82, $03
    db $40, $41, $0C, $33, $0A, $08, $42, $43, $42, $43, $0C, $A2, $00, $0C, $A2, $03
    db $42, $43, $0C, $33, $0B, $40, $41, $44, $45, $40, $41, $0C, $A2, $06, $0C, $B2
    db $0B, $0A, $42, $43, $46, $47, $42, $43, $0C, $82, $06, $0C, $B2, $0B, $0B, $40
    db $41, $12, $13, $12, $13, $0C, $C8, $0F, $06, $08, $42, $43, $14, $15, $46, $47
    db $0C, $E8, $0F, $06, $0C, $C1, $0B, $54, $55, $0C, $D2, $0F, $01, $0C, $82, $06
    db $56, $57, $0C, $F2, $0D, $40, $41, $0C, $C7, $07, $0C, $D0, $0D, $0B, $42, $00
    db $43, $0C, $E7, $07, $0C, $F0, $0D, $0C, $01, $00, $0D, $42, $43, $06, $06, $06
    db $06, $0C, $C8, $10, $06, $06, $06, $0C, $13, $0A, $0E, $00, $01, $02, $0F, $42
    db $43, $0E, $0E, $0E, $0E, $0C, $E8, $10, $0C, $E8, $10, $0C, $14, $08

; CustomAttr_Room6B: 66 bytes compressed (256 decompressed)
; Generated by tools/generate_attr_map.py from tileset 30:12 (MedalMan)
; Format: nibble-packed palette indices, 8 rows × 32 bytes
CustomAttr_Room6B:
    db $00, $01, $01, $00, $00, $00, $00, $01, $00, $00, $01, $00, $04, $00, $11, $10
    db $01, $03, $0C, $01, $03, $0C, $11, $01, $04, $0A, $11, $11, $11, $01, $41, $00
    db $01, $12, $04, $01, $41, $0C, $01, $41, $0F, $0D, $01, $41, $0F, $14, $00, $01
    db $99, $0C, $01, $49, $0F, $05, $10, $01, $42, $0B, $00, $00, $01, $33, $0A, $01
    db $E1, $0B

; Remaining bank space available for additional layouts/attrs
