; =============================================================================
; BANK $79 — STORY HOOKS: the Milly hook (S121, ROADMAP P3.16 + E7)
; Engine template (sha256-pinned, PROJECT_COMPILER §5). The data after the
; head is generated by editor2/core/milly.py (`hooks79`) from
; custom.milly_hook; with the hook OFF the whole bank stays the vanilla zeros
; (this head is not emitted at all).
;
; THE PLAYER'S LOOK (MONSTER_DATA "The player's sprite (S121)"): every draw of
; the player shape — sprite type $FFC7 = 0: the field player (bank $01, HRAM
; $FF8A = 0), the naming screen's hero icon (bank $09) — goes through bank $04
; entry 2 / 3 (type < $10: palette data_4157 = $02, frame tables data_4137 ->
; $04:$7237 = Terry). Once event flag MILLY_FLAG ($179F, extended, saved,
; zeroed by a new game) is set, type 0 is drawn with the NPC sprite's own six
; frames and palette instead; the sheet is loaded by entry 1 (field) or by the
; naming screen's table (patches/bank_009.asm region milly_naming_icon).
; The flag is set by the bedroom's east-room scene when Milayou is dragged
; into the dresser (patches/bank_00e.asm region milly_bedroom_script).
;   entry 0  MillyShapeTable  — bank $04 entry 2 / 3 (regions milly_shape_04a /
;            milly_shape_04b: `call HramScr_4126 / ld de, data_4137` ->
;            `ld hl, $7900 / rst $10`, same size): ORs the palette into
;            $FFCA and returns DE = the frame-table root.
;   entry 1  MillyPlayerSheet — bank $01 LoadFieldTilesDMA (region
;            milly_player_sheet, same size): the field sheet -> VRAM $8000,
;            and (flag set) the frame tables -> WRAM wMillyLayout.
; The frame tables live in WRAM because the metasprite builders ($0D91, bank
; $04 SaveScr_40cd) read them with bank $04 mapped; bank $04 has no room.
; Flag clear: both do exactly what the replaced code did (Terry).
; =============================================================================

SECTION "ROM Bank $079", ROMX[$4000], BANK[$79]

    db $79                          ; bank self-id (rst $10 restores by it)
    dw MillyShapeTable              ; entry 0
    dw MillyPlayerSheet             ; entry 1

MILLY_FLAG EQU $179F                ; extended flag: the player is Milly
MILLY_FLAG_MASK EQU $80 >> (MILLY_FLAG & 7)   ; FlagAddr's bit order (bank $73 entry 21)

; Entry 0. In: $FFC7 = sprite type (< $10), $FFC8 frame, $FFCA OAM attr (the
; facing flip). Out: $FFCA |= palette, DE = level-1 table for the caller's
; metasprite builder. Vanilla (HramScr_4126 + `ld de, data_4137`): palette
; data_4157[type] = $02 for all 16 types, DE = data_4137 ($04:$4137).
MillyShapeTable:
    ld a, [wExtFlags + (MILLY_FLAG - $1000) / 8]
    and MILLY_FLAG_MASK
    jr z, .vanilla
    ldh a, [$c7]
    or a
    jr nz, .vanilla                 ; not the player shape
    ld a, [wMillyLayout + 1]
    or a
    jr z, .vanilla                  ; tables not built yet (no room loaded since)
    ld hl, MillyPlayerAttr
    ldh a, [$ca]
    or [hl]
    ldh [$ca], a
    ld de, wMillyLayout
    ret
.vanilla:
    ldh a, [$ca]
    or $02                          ; data_4157[type]
    ldh [$ca], a
    ld de, $4137                    ; data_4137 (bank $04)
    ret

; Entry 1. The player's 2bpp sheet -> VRAM $8000: Terry's gfx-ID $2F00 (20
; tiles), or (flag set) the NPC sheet (16 tiles) + its frame tables -> WRAM.
MillyPlayerSheet:
    ld de, $2f00
    ld a, [wExtFlags + (MILLY_FLAG - $1000) / 8]
    and MILLY_FLAG_MASK
    jr z, .load
    ld hl, MillyLayoutImage
    ld de, wMillyLayout
    ld b, MillyLayoutImageEnd - MillyLayoutImage
.copy:
    ld a, [hl+]
    ld [de], a
    inc de
    dec b
    jr nz, .copy
    ld hl, MillyPlayerGfx
    ld a, [hl+]
    ld e, a
    ld d, [hl]
.load:
    ld hl, $8000
    jp WaitDMATransfer
