"""emitters.py — the emitter registry.

Each emitter declares the schema section it consumes and the output target
it owns (a whole generated file, or a marked @BUILD_PROJECT region inside an
existing patch file). Emitters are independent: adding a future subsystem
(e.g. custom music per ROADMAP Arc 3, or the data half of custom skills per
BATTLE_SKILL_SYSTEM §13) means registering a new emitter — no existing
emitter changes. (Design commitment S53: "emitter registry with declared
bank ownership"; reserved schema sections hard-error in project.py until an
emitter exists for them.)

Targets:
  file:patches/bank_060.asm      — whole file (template head + generated data)
  file:patches/bank_071.asm      — whole file (template head + generated tables)
  region:patches/bank_017.asm#room_palettes_a
  region:patches/bank_017.asm#room_render_tables
  region:patches/wram.asm#wram_step_counters
"""

import hashlib
import os

from . import formats as F
from . import textenc as T
from . import scriptgen as S

HERE = os.path.dirname(__file__)
TEMPLATES = os.path.join(HERE, 'templates')

# sha256 of the verbatim engine heads, extracted S53 from the user-confirmed
# patch files. The compiler refuses to run if a template drifted — the engine
# code is proven in-game; only a deliberate engine session may change it
# (then re-pin these). (Design commitment: "engine template byte-checked
# against proven source".)
TEMPLATE_SHA = {
    'bank_060_head.asm':
        None,   # pinned at first successful regression; see compiler.pin_templates
    'bank_071_head.asm':
        None,
}
TEMPLATE_SHA_FILE = os.path.join(TEMPLATES, 'PINNED_SHA256')


def template(name):
    path = os.path.join(TEMPLATES, name)
    data = open(path, 'rb').read()
    pins = {}
    if os.path.exists(TEMPLATE_SHA_FILE):
        for line in open(TEMPLATE_SHA_FILE):
            if line.strip():
                h, n = line.split()
                pins[n] = h
    got = hashlib.sha256(data).hexdigest()
    if name in pins and pins[name] != got:
        raise RuntimeError(
            f"engine template {name} does not match its pinned sha256 — "
            "the engine head is user-confirmed code; re-pin only after an "
            "engine session deliberately changes it (PROJECT_COMPILER.md §5)")
    return data.decode()


# ---------------------------------------------------------------------------
# helpers shared by emitters
# ---------------------------------------------------------------------------

def room_idx(room):
    return F.val(room['mapID']) - 0x6B


def room_tag(room):
    return f"CustomRoom{room_idx(room)}"


def banner(title, sub=None):
    bar = "; " + "=" * 77
    out = [bar, f"; {title}"]
    if sub:
        out += [f"; {s}" for s in sub]
    out.append(bar)
    return out


# ---------------------------------------------------------------------------
# bank $60 emitter — rooms + scripts + text (owns file patches/bank_060.asm)
# ---------------------------------------------------------------------------

def emit_bank_060(prj, warnings):
    rooms = prj.rooms
    lines = [template('bank_060_head.asm').rstrip('\n'), ""]

    # ---- script area ------------------------------------------------------
    lines += banner("SCRIPT DATA (generated by build_project.py)", [
        "CRITICAL: Index 0 = room entry script (runs on scroll/reload).",
        "          NPC scripts start at index 1+ (KEY_LESSONS Session 2).",
        "Master table width == compat list (legacy) or ALL rooms (default;",
        "fixes the S53 master-table overshoot for scroll in rooms >= index",
        "len(master)).  See PROJECT_COMPILER.md §scripts."])
    master_rooms = prj.master_rooms()          # list of rooms (or None = noop)
    lines.append("CustomScriptMasterTable:")
    need_noop = False
    for r in master_rooms:
        if r is None or not r.get('scripts'):
            lines.append("    dw CustomScriptNoop_PtrTable"
                         "  ; scriptless/placeholder room — safe no-op")
            need_noop = True
        else:
            lines.append(f"    dw {room_tag(r)}_ScriptPtrTable"
                         f"   ; mapID {F.hexb(F.val(r['mapID']))}")
    lines.append("")
    if need_noop:
        lines += ["CustomScriptNoop_PtrTable:",
                  "    dw CustomScriptNoop_Entry   ; [0] room entry (no-op)",
                  "CustomScriptNoop_Entry:",
                  "    dw $FFFF", ""]

    text_names = prj.text_comments()
    for r in rooms:
        if r.get('placeholder') or r.get('scripts_placement') == 'inline':
            continue
        lines += _room_scripts(prj, r, text_names, warnings)

    # ---- text area --------------------------------------------------------
    lines += banner("TEXT DATA — two-level pointer table (generated)", [
        "SaveBankAndSwitch ($00:$0940) indexes table[$C822*2] -> section,",
        "section[$C823*2] -> string (TEXT_SYSTEM.md). Flat tables crash.",
        "Custom ids $0A00+: section = hi-$0A, entry = lo",
        "(bank $04 TextQueueCheck_Ext)."])
    sections = prj.text_sections()
    lines.append("CustomTextPtrTable:")
    for si in range(len(sections)):
        lines.append(f"    dw CustomTextSection{si}")
    lines.append("")
    for si, sec in enumerate(sections):
        lines.append(f"CustomTextSection{si}:")
        for tid, entry in sec:
            lines.append(f"    dw {prj.text_label(tid)}"
                         f"   ; {F.hexw(tid)}: {entry.get('comment','')}")
        lines.append("")
        for tid, entry in sec:
            cm = f"{F.hexw(tid)} — {entry.get('comment','')}".rstrip(' —')
            lines += T.render_entry_asm(prj.text_label(tid), entry, comment=cm)
            lines.append("")

    # ---- room data area ---------------------------------------------------
    lines += banner("ROOM DATA (generated)")
    lines.append("CustomSourceMapTable:")
    for r in rooms:
        lines.append(f"    db {F.hexb(F.val(r['source_mapID']))}"
                     f"   ; {F.hexb(F.val(r['mapID']))} — {r.get('id','')}")
    lines.append("")
    lines.append("CustomRoomPtrTable:")
    for r in rooms:
        tgt = ("CustomRoomDummy_SubTable" if r.get('placeholder')
               else f"{room_tag(r)}_SubTable")
        lines.append(f"    dw {tgt}   ; {F.hexb(F.val(r['mapID']))}")
    lines.append("")

    dummy_emitted = False
    for r in rooms:
        if r.get('placeholder'):
            if not dummy_emitted:
                lines += banner("Dummy subtable — placeholder mapIDs "
                                "(never entered; all screens invalid)")
                lines.append("CustomRoomDummy_SubTable:")
                lines.append("    dw $FFFF, $FFFF, $FFFF, $FFFF,"
                             " $FFFF, $FFFF, $FFFF, $FFFF")
                lines.append("")
                dummy_emitted = True
            continue
        if r.get('scripts_placement') == 'inline':
            lines += _room_scripts(prj, r, text_names, warnings)
        lines += _room_data(prj, r)

    return "\n".join(lines) + "\n"


def _room_scripts(prj, r, text_names, warnings):
    tag = room_tag(r)
    out = [f"; --- {F.hexb(F.val(r['mapID']))} ({r.get('id','')}) scripts ---",
           f"{tag}_ScriptPtrTable:"]
    table = prj.room_script_table(r)          # ordered list of (idx, script_id)
    for idx, sid in table:
        out.append(f"    dw {tag}_Scr{idx:02d}   ; [{idx}] {sid}")
    out.append("")
    for idx, sid in table:
        script = prj.script(sid)
        out += S.emit_script(f"{tag}_Scr{idx:02d}", script['ops'],
                             text_names=text_names, warnings=warnings)
        out.append("")
    return out


def _room_data(prj, r):
    tag = room_tag(r)
    out = [f"; --- {F.hexb(F.val(r['mapID']))} ({r.get('id','')}) room data ---",
           f"{tag}_SubTable:"]
    screens = prj.room_screens(r)             # dict idx -> screen
    width = prj.subtable_width(r)
    row = []
    for i in range(width):
        row.append(f"{tag}_Screen{i}" if i in screens else "$FFFF")
    # match hand-authored style: one dw per valid screen, $FFFF runs grouped
    i = 0
    while i < width:
        if i in screens:
            out.append(f"    dw {tag}_Screen{i}")
            i += 1
        else:
            j = i
            while j < width and j not in screens:
                j += 1
            out.append("    dw " + ", ".join(["$FFFF"] * (j - i)))
            i = j
    out.append("")
    for i in sorted(screens):
        s = screens[i]
        ctr = prj.step_counter_label(r, i, s)
        lay = s['layout']
        out.append(f"{tag}_Screen{i}:")
        out.append(f"    dw {ctr}    ; step counter")
        out.append(f"    db {F.val(lay['entry'])}, {F.hexb(F.val(lay['bank']))}"
                   f"   ; step_id, tileset_bank")
        out.append(f"    dw {tag}_S{i}_NPCs")
        out.append(f"    dw {tag}_S{i}_Exits")
        out.append("")
        out.append(f"{tag}_S{i}_NPCs:")
        for n in s.get('npcs', []):
            if n['kind'] == 'spawn':
                b = F.npc_spawn_entry(n['x'], n['y'],
                                      F.val(n.get('script', 0)))
                out.append(F.db_line(b, comment=f"spawn ({n['x']},{n['y']})"
                           + (f" — {n['comment']}" if n.get('comment') else "")))
            else:
                sid = n['script']
                sidx = (0xFF if sid in (None, 'none')
                        else prj.script_index(r, sid))
                b = F.npc_entry(n.get('facing', 'down'), F.val(n['sprite']),
                                n['x'], n['y'], sidx)
                out.append(F.db_line(
                    b, comment=f"NPC ({n['x']},{n['y']}) script "
                               f"{sid if sid not in (None,'none') else 'none'}"))
        out.append("    db $FF")
        out.append("")
        out.append(f"{tag}_S{i}_Exits:")
        for e in s.get('exits', []):
            dest = prj.resolve_dest(e['dest'])
            b = F.exit_entry(e['x'], e['y'], dest,
                             F.val(e.get('gate_flag', 0)),
                             F.val(e['screen_byte']),
                             e['spawn_x'], e['spawn_y'])
            out.append(F.db_line(b, comment=e.get('comment',
                       f"exit ({e['x']},{e['y']}) -> {e['dest']}")))
        out.append("    db $FF")
        out.append("")
    return out


# ---------------------------------------------------------------------------
# bank $71 emitter — dispatch tables (owns file patches/bank_071.asm)
# ---------------------------------------------------------------------------

def emit_bank_071(prj, warnings):
    lines = [template('bank_071_head.asm').rstrip('\n'), ""]
    lines += ["; " + "-" * 77,
              "; Custom26DDTable — 8-byte $26DD-style records for mapIDs $70+,",
              "; indexed (mapID-$70): [step_id, gfx_bank, w_lo, w_hi, h_lo,",
              ";  h_hi, threshold, pad] (generated by build_project.py).",
              "; " + "-" * 77,
              "Custom26DDTable:"]
    for r in prj.rooms:
        mid = F.val(r['mapID'])
        if mid < 0x70:
            continue
        rec = r['record']
        b = F.record_26dd(F.val(rec['gfx_id']), F.val(rec['gfx_bank']),
                          F.val(rec['width_px']), F.val(rec['height_px']),
                          F.val(rec['collision_threshold']))
        lines.append(F.db_line(b, comment=F.hexb(mid)))
    lines.append("")
    lines += ["; " + "-" * 77,
              "; RoomEncTable — 3 bytes/room [enabled, gate_id, floor], indexed",
              "; (mapID-$6B). enabled=0 -> room is encounter-silent. (generated)",
              "; " + "-" * 77,
              f"ENC_TABLE_LEN EQU {len(prj.rooms)}",
              "RoomEncTable:"]
    for r in prj.rooms:
        enc = r.get('encounters') or {}
        b = F.enc_row(enc.get('enabled', False),
                      F.val(enc.get('gate_id', 0)),
                      F.val(enc.get('floor', 0)))
        state = (f"enabled, gate {F.val(enc.get('gate_id',0))}, "
                 f"floor {F.val(enc.get('floor',0))}"
                 if enc.get('enabled') else "disabled")
        lines.append(F.db_line(b, comment=f"{F.hexb(F.val(r['mapID']))} — {state}"))
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# bank $17 region emitters — per-room render tables + palette blocks
# ---------------------------------------------------------------------------

def _palette_asm(prj, pal):
    out = [f"{pal['label']}:"]
    rows = pal['colors_rgb555']
    cmts = pal.get('row_comments') or [None] * 8
    for row, cm in zip(rows, cmts):
        b = F.palette_row(row)
        out.append(F.db_line(b, comment=cm))
    return out


def emit_region_palettes_a(prj, warnings):
    out = []
    for pal in prj.palettes:
        if pal.get('placement', 'b') == 'a':
            if pal.get('comment'):
                out += [f"; {c}" for c in pal['comment']]
            out += _palette_asm(prj, pal)
            out.append("")
    return "\n".join(out).rstrip('\n') + ("\n" if out else "")


def emit_region_render_tables(prj, warnings):
    out = ["; Per-custom-room render tables (generated by build_project.py).",
           "; Indexed (wMapID - $6B) by CustomPalCheck / CustomAttrCheck",
           "; (patches/bank_017.asm engine code). ptr $0000 / bank $00 =",
           "; borrow the vanilla source-map palette/attr. One row per room.",
           "CustomRoomPalPtr:"]
    for r in prj.rooms:
        pal = prj.room_palette(r)
        tgt = pal['label'] if pal else "$0000"
        why = pal['id'] if pal else "borrow vanilla palette"
        out.append(f"    dw {tgt}    ; {F.hexb(F.val(r['mapID']))} — {why}")
    out.append("")
    out.append("CustomRoomAttr:")
    for r in prj.rooms:
        at = (r.get('render') or {}).get('attr')
        if at:
            b = [F.val(at['bank']), F.val(at['base_entry'])]
            cm = (f"{F.hexb(F.val(r['mapID']))} -> bank "
                  f"{F.hexb(F.val(at['bank']))}, attr base entry "
                  f"{F.val(at['base_entry'])}")
        else:
            b, cm = [0, 0], (f"{F.hexb(F.val(r['mapID']))} — vanilla attr "
                             "fallback")
        out.append(F.db_line(b, comment=cm))
    out.append("")
    for pal in prj.palettes:
        if pal.get('placement', 'b') == 'b':
            if pal.get('comment'):
                out += [f"; {c}" for c in pal['comment']]
            out += _palette_asm(prj, pal)
            out.append("")
    return "\n".join(out).rstrip('\n') + "\n"


# ---------------------------------------------------------------------------
# wram region emitter — custom step counters ($DE74+, S55-vetted block;
# ROOM_DATA_FORMAT "Room State System": NOT SRAM-persistent)
# ---------------------------------------------------------------------------

def emit_region_wram_steps(prj, warnings):
    """Step-counter labels at exact addresses inside the fixed-size region
    ($DE74.., S55-vetted — see patches/wram.asm banner; NOT SRAM-persistent).
    Holes between explicit addresses become `ds` fillers so every label
    lands at its declared address; the region is padded to its fixed size
    so wRoomRecScratch stays pinned at $DE7B (label-resolved by banks $00/$0B/
    $71 reads it by that address)."""
    from .project import STEP_COUNTER_BASE
    alloc = prj.step_counter_allocation()      # ordered [(label, addr, cm)]
    size = prj.wram_region_size
    out, cursor = [], STEP_COUNTER_BASE
    for label, addr, cm in alloc:
        if addr > cursor:
            out.append(f"    ds {addr - cursor} ; reserved hole "
                       "(explicit addresses above leave a gap)")
        out.append(f"{label}:: db ;{addr:04x} — {cm}")
        cursor = addr + 1
    end = STEP_COUNTER_BASE + size
    if cursor < end:
        out.append(f"    ds {end - cursor} ; reserved (region size fixed so "
                   "wRoomRecScratch stays at $DE7B — PROJECT_COMPILER.md)")
    return "\n".join(out) + "\n"


REGISTRY = [
    # (name, schema_section, target, function, owned_banks)
    ("rooms60", "custom.rooms", "file:patches/bank_060.asm",
     emit_bank_060, [0x60]),
    ("dispatch71", "custom.rooms", "file:patches/bank_071.asm",
     emit_bank_071, [0x71]),
    ("palettes_a", "custom.palettes",
     "region:patches/bank_017.asm#room_palettes_a", emit_region_palettes_a,
     [0x17]),
    ("render17", "custom.rooms",
     "region:patches/bank_017.asm#room_render_tables",
     emit_region_render_tables, [0x17]),
    ("wram_steps", "custom.rooms",
     "region:patches/wram.asm#wram_step_counters", emit_region_wram_steps,
     []),
]
