"""sprite_bank.py — cross-bank sprite OVERFLOW allocator (the GFX-2 backbone).

The fundamental capability for bulk DWM2 sprite import: place an encoded sprite
stream into a RESERVED overflow bank, build that bank's pointer table at $4001,
and hand back a gfx-ID (bank<<8 | index) that the vanilla resolver
(`DecompressTileLayout` @ $00:$1627) chases with NO bank-validity gating — so the
same mechanism repoints ANY monster's BATTLE gfx-ID ($00:$2B9F) or FOLLOWER
gfx-ID ($01:$49DF), regardless of which bank its original art lived in.

Why a separate overflow region (vs. same-bank free space): the 221 battle sprites
are spread across banks $2F,$32-$36 and followers across $2E,$2F,$38-$3A, each
with only small trailing free space. To swap arbitrary / many monsters you need a
dedicated, multi-bank allocator. The banks below are the EDITOR_DESIGN §8 canonical
reservation ($7E-$7F monster-sprite overflow, then the $7C/$7A/$79 expansion
reserve) — so this aligns with the planned editor SpritePanel backend, stays
additive (never resizes the species tables, so it does NOT block new-species
addition), and never touches breeding ($69) / custom-room ($6A-$6E) / text banks.

Bank layout (per overflow bank):
    $4000        db <bank>            ; self-ID (resolver ignores it; convention)
    $4001..      dw entry0, entry1..  ; pointer table, index*2 (resolver reads here)
    <streams>    contiguous LZ streams the pointers target
    ds ...       zero pad to $8000

The allocator is index-agnostic and count-agnostic (no hardcoded 221): callers
ask for a placement and get back a gfx-ID. Deterministic: same input -> same
layout -> same bytes.
"""
from __future__ import annotations

BANK_SIZE = 0x4000
PTBL_BASE = 0x4001
BANK_TOP = 0x8000

# EDITOR_DESIGN §8 reserved map, in fill priority order:
#   $7E-$7F = monster-sprite overflow ; $7C,$7A,$79 = expansion reserve.
DEFAULT_OVERFLOW_BANKS = [0x7E, 0x7F, 0x7C, 0x7A, 0x79]


class SpriteOverflowAllocator:
    def __init__(self, banks=None):
        self.banks = list(banks if banks is not None else DEFAULT_OVERFLOW_BANKS)
        self.placed: dict[int, list[tuple[str, bytes]]] = {b: [] for b in self.banks}

    def _bank_used(self, b: int) -> int:
        """Bytes consumed if the bank were emitted now: $4000 marker + pointer
        table (2 B/entry) + all stream bytes."""
        entries = self.placed[b]
        return 1 + len(entries) * 2 + sum(len(s) for _, s in entries)

    def add(self, stream: bytes, label: str) -> int:
        """Place `stream` (header+body) in the first overflow bank with room.
        Returns the gfx-ID (bank<<8 | index). Cost = stream + its 2-byte pointer."""
        cost = len(stream) + 2
        for b in self.banks:
            if self._bank_used(b) + cost <= BANK_SIZE:
                idx = len(self.placed[b])
                if idx > 0xFF:
                    continue  # index is one byte in the gfx-ID
                self.placed[b].append((label, stream))
                return (b << 8) | idx
        raise RuntimeError(
            f"no overflow bank fits a {len(stream)}-byte stream "
            f"(banks {[hex(x) for x in self.banks]} full)")

    def used_banks(self) -> list[int]:
        return [b for b in self.banks if self.placed[b]]

    def layout(self, b: int):
        """Return [(label, stream, local_addr)] for bank b with final addresses."""
        entries = self.placed[b]
        addr = PTBL_BASE + len(entries) * 2  # streams start after the pointer table
        out = []
        for label, s in entries:
            out.append((label, s, addr))
            addr += len(s)
        return out

    def emit_asm(self, b: int) -> str:
        """Emit a complete RGBDS source file for overflow bank b."""
        entries = self.layout(b)
        ptr_label = f"SpriteOverflowPtrs_{b:02X}"
        lines = [
            f"; =============================================================================",
            f"; OVERFLOW BANK ${b:02X} - relocated / custom monster sprite streams",
            f"; =============================================================================",
            f"; Generated by dwm/sprite_bank.py (cross-bank sprite allocator, GFX-2 backbone).",
            f"; EDITOR_DESIGN §8 reserved monster-sprite overflow region.",
            f"; Pointer table at $4001 (resolver reads $<bank>:$4001 + index*2); each entry",
            f"; targets an LZ stream below. Repoint a monster's gfx-ID (battle $00:$2B9F /",
            f"; follower $01:$49DF) to (${b:02X}<<8 | index) to use one of these.",
            f"; =============================================================================",
            "",
            f'SECTION "Sprite Overflow Bank ${b:02X}", ROMX[$4000], BANK[${b:02X}]',
            f"    db ${b:02X}                          ; bank self-ID at $4000 (resolver ignores)",
            "",
            f"{ptr_label}:                  ; pointer table @ $4001",
        ]
        for i, (label, _, _) in enumerate(entries):
            lines.append(f"    dw {label:<24} ; index {i} (${i:02x})")
        lines.append("")
        used = 1 + len(entries) * 2  # $4000 self-ID byte + pointer table bytes
        for label, s, addr in entries:
            lines.append(f"{label}:  ; stream @ ${addr:04x} ({len(s)} B)")
            for o in range(0, len(s), 16):
                lines.append("    db " + ", ".join(f"${x:02x}" for x in s[o:o + 16]))
            used += len(s)
        pad = BANK_SIZE - used  # bytes remaining to $8000
        lines.append("")
        lines.append(f"    ds {pad}   ; zero-pad to $8000  (used {used} B of {BANK_SIZE})")
        lines.append("")
        return "\n".join(lines)
