#!/usr/bin/env python3
"""Regenerate patches/bank_064.asm — the custom Room $6B rendered with the
Gate of Beginning maze tileset (gfx-ID $280D, bank $28 step $0D).

This is the authoring source for the gate-tile room: edit the tile arrangement
below and re-run to rewrite the patch. The room is a sandy island — sand floor,
ocean-wall border (incl. top), green trees, sand dunes, and pit holes — built
entirely from real gate maze tiles with the real gate floor palette ($17:$629D).

Tileset arrangement (bank $28 step $0D) — see GATE_GENERATION.md §7.2:
  FLOOR  $33         walkable sand        pal0
  OCEAN  $08         wall / water (<$30)  pal1   (collision threshold $30)
  TREE   $34-$37 2x2 leafy green object   pal3
  DUNE   $38-$3B 2x2 low sandy mound      pal0
  PIT    $3C-$3F 2x2 dark hole            pal0

Palette is assigned PER POSITION (not by tile-threshold) because trees need
pal3 while sharing the <-/>=threshold split with ocean/floor. See
GATE_GENERATION.md §7.1 for how the gate floor palette itself is derived.

Generated by: tools/build_gate_room.py
"""
import os, sys
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(SCRIPT_DIR, '..')
sys.path.insert(0, ROOT)
from tools.tile_layout_compiler import compile_layout
from tools.compress_tiles import compress_lz

W, H = 20, 16
FLOOR, OCEAN = 0x33, 0x08
TREE = [[0x34, 0x35], [0x36, 0x37]]   # pal3
DUNE = [[0x38, 0x39], [0x3A, 0x3B]]   # pal0
PIT  = [[0x3C, 0x3D], [0x3E, 0x3F]]   # pal0

# pal codes: 0 sand, 1 ocean, 3 green-tree
def new_screen(ocean_top, ocean_bottom):
    tile = [[FLOOR] * W for _ in range(H)]
    pal  = [[0] * W for _ in range(H)]
    for r in range(H):
        tile[r][0] = OCEAN; pal[r][0] = 1
        tile[r][W - 1] = OCEAN; pal[r][W - 1] = 1
    if ocean_top:
        for c in range(W): tile[0][c] = OCEAN; pal[0][c] = 1
    if ocean_bottom:
        for c in range(W): tile[H - 1][c] = OCEAN; pal[H - 1][c] = 1
    return tile, pal

def place(tile, pal, quad, r0, c0, palv):
    for dr in range(2):
        for dc in range(2):
            tile[r0 + dr][c0 + dc] = quad[dr][dc]
            pal[r0 + dr][c0 + dc] = palv

# S0 (top screen): ocean top + sides, open bottom; spawn (r12,c14), exit $6C (r2,c6)
s0t, s0p = new_screen(True, False)
place(s0t, s0p, TREE, 3, 3, 3);  place(s0t, s0p, TREE, 4, 16, 3)
place(s0t, s0p, DUNE, 9, 6, 0);  place(s0t, s0p, PIT, 6, 10, 0)
# S1 (bottom screen): ocean sides + bottom, open top; spawn (r6,c10), exit GreatTree (r14,c6)
s1t, s1p = new_screen(False, True)
place(s1t, s1p, TREE, 2, 15, 3); place(s1t, s1p, DUNE, 4, 4, 0); place(s1t, s1p, PIT, 9, 10, 0)

def gen_attr(pal_grid):
    """Pack a 16x20 per-position palette grid into the 256-byte attr block
    (8 attr-rows x 2 half-rows x 10 col-pairs, high nibble = left tile pal)."""
    out = bytearray(256)
    for ar in range(8):
        for half in range(2):
            tr = ar * 2 + half
            base = ar * 32 + half * 16
            for cp in range(10):
                lp = pal_grid[tr][cp * 2]; rp = pal_grid[tr][cp * 2 + 1]
                out[base + cp] = ((lp & 0xF) << 4) | (rp & 0xF)
    return bytes(out)

lay0 = compile_layout(s0t); lay1 = compile_layout(s1t)
attr0 = bytes(compress_lz(gen_attr(s0p))); attr1 = bytes(compress_lz(gen_attr(s1p)))

def blk(label, data, comment):
    out = ['%s:  ; %s' % (label, comment)]
    for i in range(0, len(data), 16):
        out.append('    db ' + ', '.join('$%02X' % b for b in data[i:i + 16]))
    return '\n'.join(out)

bank = '''; =============================================================================
; BANK $64 — Custom Room $6B layout + attr (Gate of Beginning: sandy island)
;   graphics = gfx-ID $280D (bank $28 step $0D); BG palette = real gate (slots 0-3).
;   Per-position palette (attr): floor/dune/pit = pal0 (sand), ocean = pal1 (blue),
;   tree = pal3 (green). Objects: TREE metatile $34-$37 (pal3), DUNE $38-$3B (pal0),
;   PIT $3C-$3F. Ocean wall ($08) borders all edges. 2 vertical screens.
; Regenerate with: python3 tools/build_gate_room.py   (see GATE_GENERATION.md §7.2)
; Engine reads via DecompressTileLayout ($1627): D=bank($64), E=entry index.
; =============================================================================
SECTION "ROM Bank $064", ROMX[$4000], BANK[$64]
    db $64  ; bank self-ID
    dw CustomLayout_Room6B_S0
    dw CustomAttr_Room6B_S0
    dw CustomLayout_Room6B_S1
    dw CustomAttr_Room6B_S1

'''
bank += blk('CustomLayout_Room6B_S0', lay0, 'top screen (LZSS)') + '\n\n'
bank += blk('CustomAttr_Room6B_S0', attr0, 'per-position sand/ocean/tree (LZSS)') + '\n\n'
bank += blk('CustomLayout_Room6B_S1', lay1, 'bottom screen (LZSS)') + '\n\n'
bank += blk('CustomAttr_Room6B_S1', attr1, 'per-position sand/ocean/tree (LZSS)') + '\n'

if __name__ == '__main__':
    out_path = os.path.join(ROOT, 'patches', 'bank_064.asm')
    with open(out_path, 'w') as f:
        f.write(bank)
    print('wrote %s (lay0=%d lay1=%d attr0=%d attr1=%d)' %
          (out_path, len(lay0), len(lay1), len(attr0), len(attr1)))
