#!/usr/bin/env python3
"""Build a combined tileset from a multi-tileset editor export.

Takes the JSON export from DWM1_Multi_Tileset_Editor and produces:
  - bank_067.asm: Combined GFX data (cherry-picked 2bpp tiles, LZSS compressed)
  - Updated bank_064.asm: Layout + attr data for the combined room
  - palette_colors.inc: 64 bytes of merged palette color data for bank $17

The editor export format:
  {
    "palette": [{"slot":0, "ts":"29:01", "idx":42, "pal":3, "walkable":true}, ...],
    "layout": [[0, 1, 2, ...], ...],  // 16 rows × 20 cols, indices into palette
    "markers": [{"type":"spawn", "x":7, "y":6}, ...]
  }

Tileset key format: "bank_hex:gfx_step_decimal"
  e.g., "30:12" = bank $30, GFX step_id 12 (decimal) = $0C (hex)

Usage:
  python3 tools/build_combined_tileset.py export.json
  python3 tools/build_combined_tileset.py export.json --out-dir patches/
  python3 tools/build_combined_tileset.py export.json --info  # just show stats

Generated by: tools/build_combined_tileset.py
"""
import json, os, sys, argparse
from collections import OrderedDict

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.join(SCRIPT_DIR, '..')
ROM_PATH = os.path.join(ROOT_DIR, 'data', 'DWM-original.gbc')

sys.path.insert(0, ROOT_DIR)
from tools.compress_tiles import compress_lz
from tools.decompress_tiles import decompress_lz


# ---------------------------------------------------------------------------
# Tileset key parsing
# ---------------------------------------------------------------------------

def parse_ts_key(ts_key):
    """Parse editor tileset key "bank_hex:gfx_step_decimal" → (bank, step_id).

    The editor encodes keys as bank in hex, GFX step_id in decimal.
    e.g., "30:12" → bank=0x30, step=12(dec)=0x0C(hex)
    """
    parts = ts_key.split(':')
    bank = int(parts[0], 16)
    gfx_step = int(parts[1])  # decimal, NOT hex
    return bank, gfx_step


# ---------------------------------------------------------------------------
# 2bpp tile extraction
# ---------------------------------------------------------------------------

def extract_tile_gfx(rom, bank, gfx_step, tile_idx):
    """Extract 16 bytes of 2bpp pixel data for a single 8×8 tile.

    Args:
        rom: full ROM bytes
        bank: tileset bank number
        gfx_step: GFX step_id (from $26DD table, passed to DecompressTileLayout)
        tile_idx: tile index within the tileset (0-127)

    Returns:
        bytes: 16 bytes of 2bpp tile data
    """
    result = decompress_lz(rom, bank, gfx_step)
    if result is None:
        raise ValueError(f"Failed to decompress tileset bank ${bank:02X} step ${gfx_step:02X}")
    data, _ = result
    if len(data) != 2048:
        raise ValueError(f"Expected 2048 bytes, got {len(data)} from bank ${bank:02X} step ${gfx_step:02X}")
    offset = tile_idx * 16
    return data[offset:offset + 16]


# ---------------------------------------------------------------------------
# Palette color extraction
# ---------------------------------------------------------------------------

def get_palette_colors(rom, ts_key):
    """Get the 8-palette color set (64 bytes) for a tileset.

    For ROM tilesets: looks up the tileset's mapID via $26DD, then reads
    pal_ptr from bank $17's attr step entry.
    For EXT: tilesets: reads from the extracted palette JSON.

    Returns: dict mapping pal_number (0-7) → list of 4 RGB15 values (each 2 bytes)
    """
    if ts_key.startswith('EXT:'):
        # External tileset — read palette from extracted JSON
        ext_name = ts_key.split(':')[1]
        pal_json = os.path.join(ROOT_DIR, 'extracted', 'custom_tilesets',
                                f'{ext_name}_palettes.json')
        if not os.path.exists(pal_json):
            raise ValueError(f"External tileset {ts_key}: palette file not found")
        import json as _json
        with open(pal_json) as f:
            pal_data = _json.load(f)
        colors = {}
        # Use per-tile exact colors: for each palette group, collect ALL colors
        # used by tiles in that group and pick the 4 most representative
        if 'tiles' in pal_data:
            from collections import Counter as _Counter
            group_colors = {}  # group → list of all tile color sets
            for tidx_str, tinfo in pal_data['tiles'].items():
                g = tinfo.get('pal_group', 0)
                if g not in group_colors:
                    group_colors[g] = _Counter()
                for c in tinfo['colors']:
                    group_colors[g][tuple(c)] += 1
            for group, color_freq in group_colors.items():
                # Take the 4 most common colors in this group
                top4 = [c for c, _ in color_freq.most_common(4)]
                while len(top4) < 4:
                    top4.append(top4[-1] if top4 else (0, 0, 0))
                # Sort by luminance (lightest first)
                top4.sort(key=lambda c: c[0]*0.299+c[1]*0.587+c[2]*0.114, reverse=True)
                pal_colors = []
                for r, g_val, b in top4:
                    gr, gg, gb = min(31, r//8), min(31, g_val//8), min(31, b//8)
                    val = (gr & 0x1F) | ((gg & 0x1F) << 5) | ((gb & 0x1F) << 10)
                    pal_colors.append((val & 0xFF, (val >> 8) & 0xFF))
                colors[group] = pal_colors
        else:
            # Fallback to old group-average format
            for group_str, rgb_list in pal_data.get('palette_colors', {}).items():
                group = int(group_str)
                pal_colors = []
                for r, g_val, b in rgb_list:
                    val = (min(31,r) & 0x1F) | ((min(31,g_val) & 0x1F) << 5) | ((min(31,b) & 0x1F) << 10)
                    pal_colors.append((val & 0xFF, (val >> 8) & 0xFF))
                colors[group] = pal_colors
        for i in range(8):
            if i not in colors:
                colors[i] = [(0, 0)] * 4
        return colors, 0
    bank, gfx_step = parse_ts_key(ts_key)

    # Find which mapID uses this bank+step in the $26DD table
    mapid = None
    for mid in range(107):
        off = 0x26DD + mid * 8
        if rom[off] == gfx_step and rom[off + 1] == bank:
            mapid = mid
            break

    if mapid is None:
        raise ValueError(f"No mapID found for tileset {ts_key} (bank ${bank:02X} step ${gfx_step:02X})")

    # Read pal_ptr from bank $17's AttrPtrTable
    base17 = 0x17 * 0x4000
    attr_table_addr = 0x476F
    ptr_off = base17 + attr_table_addr - 0x4000 + mapid * 2
    room_ptr = rom[ptr_off] | (rom[ptr_off + 1] << 8)

    if room_ptr == 0xFFFF:
        raise ValueError(f"MapID ${mapid:02X} has no attr entry")

    # Navigate to screen 0, step 0's pal_ptr
    scr_off = base17 + room_ptr - 0x4000
    scr0_ptr = rom[scr_off] | (rom[scr_off + 1] << 8)
    if scr0_ptr == 0xFFFF or scr0_ptr < 0x4000:
        raise ValueError(f"MapID ${mapid:02X} screen 0 invalid")

    step_off = base17 + scr0_ptr - 0x4000
    # Skip 2-byte WRAM addr
    step_off += 2
    # Step entry: [attr_idx:1, attr_bank:1, pal_ptr_lo:1, pal_ptr_hi:1]
    pal_ptr = rom[step_off + 2] | (rom[step_off + 3] << 8)

    # Read 64 bytes of palette color data from bank $17
    pal_off = base17 + pal_ptr - 0x4000
    colors = {}
    for pal in range(8):
        pal_colors = []
        for c in range(4):
            lo = rom[pal_off + pal * 8 + c * 2]
            hi = rom[pal_off + pal * 8 + c * 2 + 1]
            pal_colors.append((lo, hi))
        colors[pal] = pal_colors

    return colors, pal_ptr


# ---------------------------------------------------------------------------
# Core builder
# ---------------------------------------------------------------------------

def build_combined(export_data, rom):
    """Build all combined tileset data from editor export.

    Returns a dict with:
        gfx_bytes: raw 2bpp combined tileset (up to 2048 bytes)
        layout_20x16: remapped 20×16 layout
        attr_256: 256-byte nibble-packed attr map
        palette_64: 64-byte merged palette color data
        threshold: collision threshold value
        tile_count: number of unique tiles
        remap: mapping from old palette index → new sorted index
        source_tilesets: set of unique tileset keys used
    """
    palette = export_data['palette']
    layout = export_data['layout']

    if len(palette) > 128:
        raise ValueError(f"Combined palette has {len(palette)} tiles (max 128)")
    if len(layout) != 16 or any(len(r) != 20 for r in layout):
        raise ValueError(f"Layout must be 20×16, got {len(layout[0]) if layout else '?'}×{len(layout)}")

    # --- Step 1: Extract 2bpp data for each palette entry ---
    tile_data = []  # list of (16-byte data, pal, walkable, ts_key, idx)
    gfx_cache = {}  # cache decompressed tilesets

    for entry in palette:
        ts_key = entry['ts']
        idx = entry['idx']
        pal = entry.get('pal', 0)
        walkable = entry.get('walkable', True)
        # Override walkability if user set it in editor
        if 'walk' in entry:
            walkable = entry['walk']

        if ts_key.startswith('EXT:'):
            # External tileset — read from extracted 2bpp file
            ext_name = ts_key.split(':')[1]
            cache_key = ('EXT', ext_name)
            if cache_key not in gfx_cache:
                bpp_path = os.path.join(ROOT_DIR, 'extracted', 'custom_tilesets',
                                        f'{ext_name}_tiles.2bpp')
                if not os.path.exists(bpp_path):
                    raise ValueError(f"External tileset {ts_key}: file not found at {bpp_path}")
                gfx_cache[cache_key] = open(bpp_path, 'rb').read()
            tileset_data = gfx_cache[cache_key]
        else:
            # ROM tileset — decompress from ROM
            bank, gfx_step = parse_ts_key(ts_key)
            cache_key = (bank, gfx_step)
            if cache_key not in gfx_cache:
                result = decompress_lz(rom, bank, gfx_step)
                if result is None:
                    raise ValueError(f"Failed to decompress {ts_key}")
                gfx_cache[cache_key] = result[0]
            tileset_data = gfx_cache[cache_key]

        tile_bytes = tileset_data[idx * 16:(idx + 1) * 16]
        tile_data.append((tile_bytes, pal, walkable, ts_key, idx))

    # (Step 1b removed: k-means auto-correction no longer needed.
    #  NORDEN_palettes.json now uses exact-color grouping with subset merging.)

    # --- Step 2: Sort — WALL tiles first, walkable after ---
    # Game collision: tile < threshold = blocked ($FF), tile >= threshold = walkable ($0F)
    # So wall tiles get low indices, walkable tiles get high indices
    indexed_tiles = list(enumerate(tile_data))
    wall_tiles = [(i, t) for i, t in indexed_tiles if not t[2]]
    walkable_tiles = [(i, t) for i, t in indexed_tiles if t[2]]

    sorted_tiles = wall_tiles + walkable_tiles
    threshold = len(wall_tiles)

    # Build remap: old_index → new_index
    remap = {}
    for new_idx, (old_idx, _) in enumerate(sorted_tiles):
        remap[old_idx] = new_idx

    # --- Step 2b: Avoid animated tile indices ---
    # The Castle VRAM handler (mapID $00, which runs for custom rooms via
    # MapIDClampForDispatch) animates tile indices 77-78 by rotating their
    # pixel data in VRAM. Any custom tile at those indices gets animated.
    # Fix: shift tiles past the animated range by inserting blanks.
    ANIMATED_INDICES = {77, 78}
    final_idx_for_tile = {}  # sorted_tiles position → final GFX index
    final_idx = 0
    for pos in range(len(sorted_tiles)):
        while final_idx in ANIMATED_INDICES:
            final_idx += 1
        final_idx_for_tile[pos] = final_idx
        final_idx += 1
    total_gfx_tiles = final_idx  # includes gaps for animated indices

    # Update remap: old_palette_index → final GFX index
    for new_pos, (old_idx, _) in enumerate(sorted_tiles):
        remap[old_idx] = final_idx_for_tile[new_pos]

    if any(final_idx_for_tile[i] != i for i in range(len(sorted_tiles))):
        print(f"Shifted tiles to avoid animated indices {sorted(ANIMATED_INDICES)}",
              file=sys.stderr)

    # --- Step 3: Build combined GFX ---
    gfx_bytes = bytearray()
    tile_pos = 0
    for gfx_idx in range(total_gfx_tiles):
        if gfx_idx in ANIMATED_INDICES:
            gfx_bytes.extend(b'\x00' * 16)  # blank at animated index
        else:
            gfx_bytes.extend(sorted_tiles[tile_pos][1][0])
            tile_pos += 1

    # Pad to 2048 bytes (128 tiles) with blank tiles
    while len(gfx_bytes) < 2048:
        gfx_bytes.extend(b'\x00' * 16)

    # --- Step 4: Remap layout ---
    layout_remapped = []
    for row in layout:
        new_row = []
        for tile_idx in row:
            if tile_idx in remap:
                new_row.append(remap[tile_idx])
            else:
                new_row.append(0)  # fallback
        layout_remapped.append(new_row)

    # --- Step 5: Determine palette slot remapping ---
    source_tilesets = set(entry['ts'] for entry in palette)

    # Collect unique (ts, pal) pairs from USED tiles, ordered by frequency
    from collections import Counter
    pal_usage = Counter()
    for row in layout:
        for tile_idx in row:
            if tile_idx < len(palette):
                p = palette[tile_idx]
                pal_usage[(p['ts'], p['pal'])] += 1

    # --- Palette merging: merge groups whose colors are subsets ---
    # For EXT: tilesets, get per-tile exact colors; for ROM tilesets, each (ts,pal) is distinct
    import json as _json
    _ext_cache = {}
    def _get_tile_colors(ts_key, tile_idx):
        if not ts_key.startswith('EXT:'):
            return None  # ROM palettes don't merge
        ext_name = ts_key.split(':')[1]
        if ext_name not in _ext_cache:
            pj = os.path.join(ROOT_DIR, 'extracted', 'custom_tilesets', f'{ext_name}_palettes.json')
            if os.path.exists(pj):
                with open(pj) as f: _ext_cache[ext_name] = _json.load(f)
            else: _ext_cache[ext_name] = {}
        ti = _ext_cache.get(ext_name, {}).get('tiles', {}).get(str(tile_idx))
        return set(tuple(c) for c in ti['colors']) if ti else None

    # Collect color sets per (ts, pal) from used tiles
    group_colors = {}  # (ts, pal) → set of RGB tuples
    for row in layout:
        for tile_idx in row:
            if tile_idx < len(palette):
                p = palette[tile_idx]
                key = (p['ts'], p['pal'])
                if key not in group_colors:
                    group_colors[key] = set()
                tc = _get_tile_colors(p['ts'], p['idx'])
                if tc:
                    group_colors[key] |= tc

    # Build merge map: check if any EXT group is a subset of another
    merge_map = {}  # (ts, pal) → (ts, merged_pal)
    ext_keys = [k for k in group_colors if k[0].startswith('EXT:')]
    for k1 in ext_keys:
        if k1 in merge_map:
            continue
        for k2 in ext_keys:
            if k1 != k2 and k1[0] == k2[0] and k2 not in merge_map:
                if group_colors[k1] < group_colors[k2]:  # strict subset
                    merge_map[k1] = k2
                    break

    if merge_map:
        merged_str = ', '.join(f'{k[1]}→{v[1]}' for k,v in merge_map.items())
        print(f"Palette merge: {merged_str}")
        # Update pal_usage with merged keys
        merged_usage = Counter()
        for key, count in pal_usage.items():
            target = merge_map.get(key, key)
            merged_usage[target] += count
        pal_usage = merged_usage

    # Assign slots by usage frequency
    pal_slot_map = OrderedDict()
    for (ts_key, src_pal), _ in pal_usage.most_common():
        if len(pal_slot_map) < 8:
            pal_slot_map[(ts_key, src_pal)] = len(pal_slot_map)

    # Also add unused pairs if room
    for _, (_, tile_info) in enumerate(sorted_tiles):
        _, src_pal, _, ts_key, _ = tile_info
        key = merge_map.get((ts_key, src_pal), (ts_key, src_pal))
        if key not in pal_slot_map and len(pal_slot_map) < 8:
            pal_slot_map[key] = len(pal_slot_map)

    if len(pal_usage) > 8:
        print(f"WARNING: {len(pal_usage)} unique palette slots needed (max 8). "
              f"Some tiles will use wrong colors.", file=sys.stderr)

    # --- Step 6: Build tile→COMBINED palette mapping ---
    sorted_pal = {}
    for pos, (_, tile_info) in enumerate(sorted_tiles):
        final_idx = final_idx_for_tile[pos]
        _, src_pal, _, ts_key, _ = tile_info
        key = merge_map.get((ts_key, src_pal), (ts_key, src_pal))
        combined_slot = pal_slot_map.get(key, 0)
        if combined_slot >= 8:
            combined_slot = 0
        sorted_pal[final_idx] = combined_slot

    attr_256 = generate_attr_data(layout_remapped, sorted_pal)

    # Compute merged palette colors (must happen before Step 6b so
    # ext_rearranged is available for 2bpp re-encoding)
    palette_64, pal_remap_info, ext_rearranged = merge_palette_colors(
        rom, pal_slot_map, source_tilesets, export_palette=palette, merge_map=merge_map
    )

    # --- Step 6b: Re-encode EXT: tile 2bpp data for palette index alignment ---
    # When a tile's colors are a subset of the palette slot's colors,
    # the 2bpp indices won't align (tile index 0 might be grey, but palette
    # index 0 is white). Re-encode each EXT: tile's 2bpp data so pixel
    # indices match the palette slot's color positions.
    #
    # Uses the canonical palette colors from the JSON's palette_colors field
    # (exact-color grouping, not computed from tile colors).
    for pos, (old_idx, tile_info) in enumerate(sorted_tiles):
        tile_data_16, src_pal, walkable, ts_key, orig_idx = tile_info
        final_gfx_idx = final_idx_for_tile[pos]
        if not ts_key.startswith('EXT:'):
            continue  # ROM tiles already match their palette

        ext_name = ts_key.split(':')[1]
        pd = _ext_cache.get(ext_name, {})

        # Get canonical palette colors for this group
        # For EXT tiles: use the REARRANGED palette (0↔1 swapped) so that
        # the lightest color maps to index 1 (forced by game engine)
        key = merge_map.get((ts_key, src_pal), (ts_key, src_pal))
        effective_pal = key[1]

        if key in ext_rearranged:
            slot_colors = ext_rearranged[key]
        else:
            slot_colors_raw = pd.get('palette_colors', {}).get(str(effective_pal))
            if not slot_colors_raw:
                continue
            slot_colors = [tuple(c) for c in slot_colors_raw]

        # Get tile's own unique colors sorted by luminance (lightest first)
        tinfo = pd.get('tiles', {}).get(str(orig_idx))
        if not tinfo:
            continue
        tc = set(tuple(c) for c in tinfo['colors'])
        tile_colors = sorted(tc, key=lambda c: c[0]*0.299+c[1]*0.587+c[2]*0.114,
                             reverse=True)
        while len(tile_colors) < 4:
            tile_colors.append(tile_colors[-1])
        tile_colors = tile_colors[:4]

        # Build remap: tile_index → palette_index (nearest color match)
        color_remap = {}
        for ti, tcol in enumerate(tile_colors):
            best_pi = 0
            best_dist = float('inf')
            for pi, pcol in enumerate(slot_colors):
                d = sum((a-b)**2 for a,b in zip(tcol, pcol))
                if d < best_dist:
                    best_dist = d
                    best_pi = pi
            color_remap[ti] = best_pi

        # Check if remap is identity (no change needed)
        if all(color_remap[i] == i for i in range(4)):
            continue

        # Re-encode the 2bpp data
        old_data = bytearray(tile_data_16)
        new_data = bytearray(16)
        for row in range(8):
            old_lo = old_data[row*2]
            old_hi = old_data[row*2+1]
            new_lo = 0
            new_hi = 0
            for col in range(8):
                bit = 7 - col
                old_ci = ((old_lo >> bit) & 1) | (((old_hi >> bit) & 1) << 1)
                new_ci = color_remap.get(old_ci, old_ci)
                new_lo |= ((new_ci & 1) << bit)
                new_hi |= (((new_ci >> 1) & 1) << bit)
            new_data[row*2] = new_lo
            new_data[row*2+1] = new_hi

        # Update gfx_bytes in place
        offset = final_gfx_idx * 16
        gfx_bytes[offset:offset+16] = new_data

    return {
        'gfx_bytes': bytes(gfx_bytes),
        'layout_20x16': layout_remapped,
        'attr_256': attr_256,
        'palette_64': palette_64,
        'palette_info': pal_remap_info,
        'threshold': threshold,
        'tile_count': len(palette),
        'remap': remap,
        'source_tilesets': source_tilesets,
        'pal_slot_map': pal_slot_map,
    }


def generate_attr_data(layout_20x16, tile_pal, default_pal=0):
    """Generate 256-byte nibble-packed attr map.

    Same format as generate_attr_map.py: 8 rows × 32 bytes,
    each row = [10 even-row bytes][6 pad][10 odd-row bytes][6 pad].
    Each byte: high nibble = left tile pal, low nibble = right tile pal.
    """
    output = bytearray(256)

    for attr_row in range(8):
        for half in range(2):
            tile_row = attr_row * 2 + half
            base = attr_row * 32 + half * 16

            for col_pair in range(10):
                left_col = col_pair * 2
                right_col = col_pair * 2 + 1

                left_tile = layout_20x16[tile_row][left_col]
                right_tile = layout_20x16[tile_row][right_col]

                left_pal = tile_pal.get(left_tile, default_pal)
                right_pal = tile_pal.get(right_tile, default_pal)

                output[base + col_pair] = (left_pal << 4) | (right_pal & 0xF)

    return bytes(output)


def merge_palette_colors(rom, pal_slot_map, source_tilesets, export_palette=None, merge_map=None):
    """Merge palette colors from multiple source tilesets.

    For EXT: tilesets, reads exact palette colors from the palette JSON's
    palette_colors field (exact-color grouping, not k-means averages).
    For ROM tilesets, reads from the ROM's palette data.

    CRITICAL: The game engine forces BG palette color index 1 to a shared
    value ($6BFF = (248,248,208)) at runtime, overwriting whatever we set.
    For EXT tilesets, we swap colors 0↔1 so the lightest color (closest to
    the forced value) goes to index 1 (where it'll be overwritten with
    something similar), and the second color goes to index 0 (preserved).
    ROM tilesets already account for this in their original encoding.
    """
    if merge_map is None:
        merge_map = {}

    # Load EXT palette JSON data
    pal_json_cache = {}
    if export_palette:
        for entry in export_palette:
            ts_key = entry['ts']
            if not ts_key.startswith('EXT:'):
                continue
            ext_name = ts_key.split(':')[1]
            if ext_name not in pal_json_cache:
                pj = os.path.join(ROOT_DIR, 'extracted', 'custom_tilesets',
                                  f'{ext_name}_palettes.json')
                if os.path.exists(pj):
                    with open(pj) as f:
                        pal_json_cache[ext_name] = json.load(f)

    # Load ROM palette colors for non-EXT tilesets
    pal_color_cache = {}
    for ts_key in source_tilesets:
        if ts_key.startswith('EXT:'):
            continue
        try:
            colors, pal_ptr = get_palette_colors(rom, ts_key)
            pal_color_cache[ts_key] = colors
        except ValueError as e:
            print(f"WARNING: {e}", file=sys.stderr)

    # Build 64-byte output + track rearranged palettes for EXT tiles
    output = bytearray(64)
    info = {}
    ext_rearranged = {}  # (ts_key, pal) → rearranged [4 × (r,g,b)]

    for (ts_key, src_pal), combined_slot in pal_slot_map.items():
        if combined_slot >= 8:
            break

        if ts_key.startswith('EXT:'):
            # Read exact palette colors from the JSON's palette_colors field
            ext_name = ts_key.split(':')[1]
            pd = pal_json_cache.get(ext_name, {})
            pal_colors_rgb = pd.get('palette_colors', {}).get(str(src_pal))
            if pal_colors_rgb:
                # Rearrange: swap positions 0↔1 so lightest color goes to
                # index 1 (forced by game) and second color to index 0 (preserved)
                rearranged = list(pal_colors_rgb[:4])
                while len(rearranged) < 4:
                    rearranged.append(rearranged[-1])
                rearranged[0], rearranged[1] = rearranged[1], rearranged[0]
                ext_rearranged[(ts_key, src_pal)] = [tuple(c) for c in rearranged]

                for ci, color in enumerate(rearranged):
                    r, g, b = color
                    gr, gg, gb = min(31, r // 8), min(31, g // 8), min(31, b // 8)
                    val = (gr & 0x1F) | ((gg & 0x1F) << 5) | ((gb & 0x1F) << 10)
                    output[combined_slot * 8 + ci * 2] = val & 0xFF
                    output[combined_slot * 8 + ci * 2 + 1] = (val >> 8) & 0xFF
                info[combined_slot] = f"{ts_key} pal {src_pal}"
        elif ts_key in pal_color_cache and src_pal in pal_color_cache[ts_key]:
            colors = pal_color_cache[ts_key][src_pal]
            for c in range(4):
                output[combined_slot * 8 + c * 2] = colors[c][0]
                output[combined_slot * 8 + c * 2 + 1] = colors[c][1]
            info[combined_slot] = f"{ts_key} pal {src_pal}"

    return bytes(output), info, ext_rearranged


# ---------------------------------------------------------------------------
# ASM output
# ---------------------------------------------------------------------------

def format_asm_db(data, label, comment="", bytes_per_line=16):
    """Format compressed data as ASM db statements."""
    lines = []
    if comment:
        lines.append(f'; {comment}')
    lines.append(f'{label}:')
    for i in range(0, len(data), bytes_per_line):
        chunk = data[i:i + bytes_per_line]
        hex_bytes = ', '.join(f'${b:02X}' for b in chunk)
        lines.append(f'    db {hex_bytes}')
    return '\n'.join(lines)


def generate_bank_067(gfx_compressed):
    """Generate bank_067.asm with combined GFX data."""
    lines = [
        '; =============================================================================',
        '; BANK $67 — Combined Tileset GFX (multi-tileset mashup)',
        '; =============================================================================',
        '; Generated by tools/build_combined_tileset.py',
        '; Format: pointer table at $4001, LZSS compressed 2bpp tile data',
        '; Entry 0: combined tileset GFX (2048 bytes decompressed = 128 tiles × 16 bytes)',
        '; Loaded by DecompressTileLayout via $26DD table entry for mapID $6B',
        '; =============================================================================',
        '',
        'SECTION "ROM Bank $067", ROMX[$4000], BANK[$67]',
        '    db $67  ; bank self-ID',
        '',
        '; Pointer table at $4001',
        '    dw CombinedGFX_Room6B',
        '',
        format_asm_db(gfx_compressed, 'CombinedGFX_Room6B',
                      f'CombinedGFX_Room6B: {len(gfx_compressed)} bytes compressed (2048 decompressed)'),
        '',
        '; Remaining bank space available for additional combined tilesets',
        '',
    ]
    return '\n'.join(lines)


def generate_bank_064(layout_compressed, attr_compressed, layout_json_name="export"):
    """Generate bank_064.asm with layout + attr data."""
    lines = [
        '; =============================================================================',
        '; BANK $64 — Custom Tile Layout + Attribute Data',
        '; =============================================================================',
        '; Layout generated by tools/build_combined_tileset.py',
        '; Attr data generated by tools/build_combined_tileset.py',
        '; Format: pointer table at $4001, LZSS compressed data',
        '; Entry 0: tile layout (512 bytes decompressed, 32×16 padded grid)',
        '; Entry 1: palette attributes (256 bytes decompressed, nibble-packed)',
        '; Engine reads via DecompressTileLayout ($1627): D=bank, E=entry index',
        '; =============================================================================',
        '',
        'SECTION "ROM Bank $064", ROMX[$4000], BANK[$64]',
        '    db $64  ; bank self-ID',
        '',
        '; Pointer table at $4001 — indexed by entry number (E register)',
        '; Entry 0: tile layout data (used by room step entry byte 0)',
        '; Entry 1: palette attribute data (used by bank $17 CustomAttrCheck)',
        '    dw CustomLayout_Room6B',
        '    dw CustomAttr_Room6B',
        '',
        format_asm_db(layout_compressed, 'CustomLayout_Room6B',
                      f'CustomLayout_Room6B: {len(layout_compressed)} bytes compressed (512 decompressed)'),
        '',
        format_asm_db(attr_compressed, 'CustomAttr_Room6B',
                      f'CustomAttr_Room6B: {len(attr_compressed)} bytes compressed (256 decompressed)'),
        '',
        '; Remaining bank space available for additional layouts/attrs',
        '',
    ]
    return '\n'.join(lines)


def generate_palette_inc(palette_64, info):
    """Generate palette color data as ASM db statements for bank $17."""
    lines = [
        '; CustomPaletteColors_6B: 64 bytes (8 palettes × 4 colors × 2 bytes)',
        '; Generated by tools/build_combined_tileset.py',
        '; Format: RGB15 LE pairs — [lo, hi] per color, 4 colors per palette',
    ]
    for slot, source in sorted(info.items()):
        lines.append(f';   Palette {slot}: from {source}')
    lines.append('CustomPaletteColors_6B:')
    for pal in range(8):
        chunk = palette_64[pal * 8:(pal + 1) * 8]
        hex_bytes = ', '.join(f'${b:02X}' for b in chunk)
        lines.append(f'    db {hex_bytes}  ; palette {pal}')
    return '\n'.join(lines)


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description='Build combined tileset from editor export')
    parser.add_argument('export_json', help='Editor export JSON file')
    parser.add_argument('--out-dir', default=None,
                        help='Output directory (default: patches/)')
    parser.add_argument('--info', action='store_true',
                        help='Show stats only, don\'t generate files')
    parser.add_argument('--rom', default=ROM_PATH,
                        help='Path to DWM-original.gbc')
    args = parser.parse_args()

    # Load export
    with open(args.export_json) as f:
        export_data = json.load(f)

    # Load ROM
    with open(args.rom, 'rb') as f:
        rom = f.read()

    palette = export_data['palette']
    layout = export_data['layout']
    markers = export_data.get('markers', [])

    print(f"Export: {len(palette)} tiles from {len(set(e['ts'] for e in palette))} tilesets",
          file=sys.stderr)
    print(f"Layout: {len(layout)}×{len(layout[0]) if layout else 0}", file=sys.stderr)

    # Build everything
    result = build_combined(export_data, rom)

    print(f"Combined tileset: {result['tile_count']} tiles", file=sys.stderr)
    print(f"Walkable: {result['threshold']} / Wall: {result['tile_count'] - result['threshold']}",
          file=sys.stderr)
    print(f"Collision threshold: {result['threshold']}", file=sys.stderr)
    print(f"Source tilesets: {', '.join(sorted(result['source_tilesets']))}", file=sys.stderr)

    if args.info:
        return

    # Compress
    from tools.tile_layout_compiler import pad_layout
    layout_padded = pad_layout(result['layout_20x16'])
    layout_compressed = compress_lz(layout_padded)
    attr_compressed = compress_lz(result['attr_256'])
    gfx_compressed = compress_lz(result['gfx_bytes'])

    print(f"\nCompression:", file=sys.stderr)
    print(f"  GFX:    2048 → {len(gfx_compressed)} bytes ({len(gfx_compressed)/2048*100:.0f}%)",
          file=sys.stderr)
    print(f"  Layout: 512 → {len(layout_compressed)} bytes ({len(layout_compressed)/512*100:.0f}%)",
          file=sys.stderr)
    print(f"  Attr:   256 → {len(attr_compressed)} bytes ({len(attr_compressed)/256*100:.0f}%)",
          file=sys.stderr)

    # Determine output directory
    out_dir = args.out_dir or os.path.join(ROOT_DIR, 'patches')
    os.makedirs(out_dir, exist_ok=True)

    # Generate ASM files
    bank067_asm = generate_bank_067(gfx_compressed)
    bank064_asm = generate_bank_064(layout_compressed, attr_compressed)

    # Palette colors
    pal_inc = generate_palette_inc(result['palette_64'], result['palette_info'])

    # Write outputs
    bank067_path = os.path.join(out_dir, 'bank_067.asm')
    bank064_path = os.path.join(out_dir, 'bank_064.asm')
    pal_path = os.path.join(out_dir, 'palette_6b.inc')

    with open(bank067_path, 'w') as f:
        f.write(bank067_asm)
    print(f"\nWritten: {bank067_path}", file=sys.stderr)

    with open(bank064_path, 'w') as f:
        f.write(bank064_asm)
    print(f"Written: {bank064_path}", file=sys.stderr)

    with open(pal_path, 'w') as f:
        f.write(pal_inc)
    print(f"Written: {pal_path}", file=sys.stderr)

    # Show $2A35 entry that needs to be written
    print(f"\n=== ROM0 $2A35 entry (mapID $6B in $26DD table) ===", file=sys.stderr)
    print(f"  Byte 0 (step_id): $00", file=sys.stderr)
    print(f"  Byte 1 (bank):    $67", file=sys.stderr)
    print(f"  Byte 6 (threshold): ${result['threshold']:02X} ({result['threshold']})", file=sys.stderr)
    entry = bytearray([0x00, 0x67, 0xA0, 0x00, 0x80, 0x00, result['threshold'], 0x00])
    print(f"  Full entry: {' '.join(f'${b:02X}' for b in entry)}", file=sys.stderr)

    # Show markers
    if markers:
        print(f"\n=== Markers ===", file=sys.stderr)
        for m in markers:
            mtype = m.get('type', '?')
            x, y = m.get('x', 0), m.get('y', 0)
            if mtype == 'exit':
                print(f"  Exit at ({x},{y}) — exit coords = ({x//2},{y//2})", file=sys.stderr)
            else:
                print(f"  {mtype} at ({x},{y})", file=sys.stderr)


if __name__ == '__main__':
    main()
