#!/usr/bin/env python3
"""Derive a room's runtime palette directly from the ROM (no SameBoy dump needed).

The GBC does not "infer" colours magically — each room supplies the real colours
for BG palette slots 0-3 (and gate floors slot 4), the engine forces two colours
in every BG palette, and slots 4-7 plus all object palettes are a shared system
set. This tool reproduces that, so the editor can colour any room from ROM alone.

Logic (verified against in-game SameBoy dumps for GreatTree/Bazaar/Farm/Stable/
gate floors):

  BG slots 0-3 (room environment):
    - normal rooms: AttrPtrTable ($17:$476F)[mapID] -> screen0 -> step entry ->
      pal_ptr -> 4 palettes (8 bytes each).
    - gate floors:  $17:$51F5[floortype] -> 4 palettes.
    Only colours 0 and 2 are real; the engine OVERWRITES:
        colour index 1 -> $6BFF   (the shared light colour)
        colour index 3 -> $0000   (black)
    in EVERY BG palette at runtime. That is the "inference" — it is a fixed rule.

  BG slots 4-7 (system): a shared set used by HUD/menus/monster display. Slots
    5/6/7 are constant across all rooms; slot 4 is usually constant but some
    rooms (e.g. gate floors) override it as a 5th environment palette.

  Object palettes: a single global block at $17:$5615 (identical in every room).

Usage:
  python3 tools/derive_room_palette.py --map 0x01      # normal room (GreatTree)
  python3 tools/derive_room_palette.py --gate 0x0D     # gate floortype $D
  python3 tools/derive_room_palette.py --map 0x04 --raw # don't force idx1/3

Generated by: tools/derive_room_palette.py
"""
import os, sys, argparse

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.join(SCRIPT_DIR, '..')
ROM_PATH = os.path.join(ROOT_DIR, 'data', 'DWM-original.gbc')

FORCE_IDX1 = 0x6BFF   # engine overwrites BG colour index 1 with this every frame
FORCE_IDX3 = 0x0000   # ...and index 3 with this
ATTR_PTR_TABLE = 0x476F   # bank $17, indexed by mapID -> room attr block
GATE_PAL_TABLE = 0x51F5   # bank $17, indexed by floortype -> 4-palette block
OBJ_PAL_BLOCK  = 0x5615   # bank $17, 8 object palettes (global)


def _f17(addr):
    return 0x17 * 0x4000 + (addr - 0x4000)


def _read_palettes(rom, ptr, n, force):
    """Read n palettes (4 colours each) starting at bank-$17 address `ptr`."""
    o = _f17(ptr)
    out = []
    for p in range(n):
        cols = []
        for c in range(4):
            v = rom[o + p * 8 + c * 2] | (rom[o + p * 8 + c * 2 + 1] << 8)
            cols.append(v)
        if force:
            cols[1] = FORCE_IDX1
            cols[3] = FORCE_IDX3
        out.append(cols)
    return out


PAL_REGION = (0x5200, 0x6300)   # bank-$17 address range where room palettes live


def _valid_pal_ptr(ptr):
    return ptr is not None and PAL_REGION[0] <= ptr < PAL_REGION[1]


def normal_room_pal_ptr(rom, mapid, max_screens=8):
    """Resolve a normal room's environment palette pointer via AttrPtrTable.

    Scans screens (some rooms, e.g. Starry Shrine, leave screen 0 empty and put
    the real data on screen 1). Returns the first screen's step-0 pal_ptr that
    lands in the palette region, or None if the room has no attr palette at all
    (e.g. the Intro, which is script-driven). Returning None is deliberate: the
    tool refuses rather than hand back a wrong/guessed palette.
    """
    base = _f17(ATTR_PTR_TABLE) + mapid * 2
    room_ptr = rom[base] | (rom[base + 1] << 8)
    if room_ptr < 0x4000 or room_ptr >= 0x8000:
        return None
    for s in range(max_screens):
        scr = _f17(room_ptr) + s * 2
        scr_ptr = rom[scr] | (rom[scr + 1] << 8)
        if scr_ptr < 0x4000 or scr_ptr >= 0x8000:
            continue                       # empty/invalid screen, try next
        step = _f17(scr_ptr) + 2           # skip 2-byte WRAM dest addr
        pal_ptr = rom[step + 2] | (rom[step + 3] << 8)
        if _valid_pal_ptr(pal_ptr):
            return pal_ptr
    return None


def derive(rom, *, mapid=None, floortype=None, force=True):
    """Return (env_palettes[4], obj_palettes[8]) for a room or gate floor.

    env_palettes are BG slots 0-3 (the room environment). Raises ValueError if
    the room has no resolvable attr palette (script-driven rooms like the Intro);
    callers get a clean refusal instead of a guessed palette. Slots 4-7 are a
    shared system set, not returned here.
    """
    if floortype is not None:
        base = _f17(GATE_PAL_TABLE) + floortype * 2
        env_ptr = rom[base] | (rom[base + 1] << 8)
        if not _valid_pal_ptr(env_ptr):
            env_ptr = None
    else:
        env_ptr = normal_room_pal_ptr(rom, mapid)
    if env_ptr is None:
        raise ValueError("no resolvable attr palette (room has no palette pointer "
                         "in its attr data; it may be unused or set at runtime by script)")

    env = _read_palettes(rom, env_ptr, 4, force)             # slots 0-3
    obj = _read_palettes(rom, OBJ_PAL_BLOCK, 8, force=False)  # global object palettes
    return env, obj


def fmt(pal):
    return ' '.join('%04x' % c for c in pal)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument('--map', type=lambda x: int(x, 0), help='normal room mapID (e.g. 0x01)')
    g.add_argument('--gate', type=lambda x: int(x, 0), help='gate floortype (e.g. 0x0D)')
    ap.add_argument('--raw', action='store_true', help='do NOT force idx1=$6BFF / idx3=$0000')
    args = ap.parse_args()

    rom = open(ROM_PATH, 'rb').read()
    try:
        env, obj = derive(rom, mapid=args.map, floortype=args.gate, force=not args.raw)
    except ValueError as e:
        label = ('gate floortype $%02X' % args.gate) if args.gate is not None else ('mapID $%02X' % args.map)
        print('=== %s ===' % label)
        print('  REFUSED: %s' % e)
        return

    label = ('gate floortype $%02X' % args.gate) if args.gate is not None else ('mapID $%02X' % args.map)
    print('=== %s ===' % label)
    print('BG slots 0-3 (environment; idx1->$6BFF, idx3->$0000 forced):')
    for i, p in enumerate(env):
        print('  slot%d  %s' % (i, fmt(p)))
    print('BG slots 4-7: shared system palettes (constant; slot 4 sometimes room-specific)')
    print('Object palettes (global, $17:$5615):')
    for i, p in enumerate(obj):
        print('  obj%d   %s' % (i, fmt(p)))


if __name__ == '__main__':
    main()
