#!/usr/bin/env python3
"""extract_room.py — clone a VANILLA room into a full project.json custom room
(P3.2b [G-J], S92 — the fork-don't-fiddle mechanism, user decision S90).

What it does (single-version clone per user decision S92 — romhack state
variants are ADDED afterwards via screens[].states, not extracted):

  1. Room record from the $00:$26DD row (gfx/dims/threshold verbatim).
  2. Screens from the bank $0B room tables — every interact/exit entry's raw
     bytes are RE-READ from the ROM and must equal extracted/map_table.json's
     recorded raws (abort on any mismatch; the npc_catalog phantom-step class
     showed dumps can drift). Interact entries emit as RAW 5-byte pass-through
     (faithful: $8F spawn-id params, $90 walk-on markers, $82 markers).
     The captured step per screen is step 0 (--step N overrides).
  3. Layouts stay REFERENCES to the vanilla tileset-bank entries (same
     DecompressTileLayout path vanilla uses — zero re-emission).
  4. Attr maps: vanilla per-screen attr (AttrPtrTable $17:$476F walk, step 0)
     decompressed and re-emitted as custom.layouts attr items (the borrow-
     vanilla $00 path derives from raw wMapID — unmeasured for clones, so the
     clone never relies on it).
  5. Palette: derive_room_palette logic (validated 30/30 vs SameBoy) → one
     custom.palettes block (8x4, idx1/idx3 forced values included).
  6. Scripts: independent decoder over the bank script table ($41BA +
     map_type*2). Param counts = decompile_script.PARAM_COUNTS overridden by
     the handler-verified editor2.core.scriptgen.OPS rows ($07:0, $41:1,
     $5A:1 — PROJECT_COMPILER §8 / S70). Segmentation is PROVEN per script:
     every branch-target param must land exactly on a decoded op boundary,
     else the tool aborts naming the suspect opcode. Branch-reached blocks
     outside the linear body are appended (per-script duplication when
     shared). Vanilla text ids pass through raw.
  7. Music: the vanilla room-BGM derivation result for the source room is
     assigned as the clone's room default (raw inbuilt id), since the custom
     BGM resolver otherwise finds no assignment for a clone mapID.
  8. Reports: orphaned story flags (every flag the scripts read/write),
     cond_branch RAM addresses, external references — the satisfy-or-strip
     list EDITOR_DESIGN §6.1 requires.

Usage:
  python3 tools/extract_room.py --source 0x06 --room-id arena_clone \
      --project editor2/example-project --print        # fragment to stdout
  ... --apply                                          # merge into project.json

Custom→custom cloning (the acceptance's second half) is --source-custom
<room_id>: the project room is deep-copied under a new id/mapID (trivial by
construction — project.json IS the semantic form).

Generated by: tools/extract_room.py
"""
import argparse
import copy
import json
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, '..'))
sys.path.insert(0, ROOT)

from editor2.core import scriptgen as SG                       # noqa: E402
from editor2.core import layouts as LAY                        # noqa: E402

ROM_PATH = os.path.join(ROOT, 'data', 'DWM-original.gbc')
MAP_TABLE = os.path.join(ROOT, 'extracted', 'map_table.json')
SCRIPT_TBL = 0x41BA         # + map_type*2 → per-map script ptr list (every script bank)


def script_bank(mid):
    """Vanilla map-script bank for a map type — bank $04 MapTypeDispatch
    (BANK04_SCRIPT_ENGINE "Script Data Banks"): < $06 → $0C, < $20 → $0D,
    < $40 → $0E, else $0F. Each bank's master table sits at $41BA and is
    indexed by the FULL map type (rows outside the bank's range are filler).
    S96: the extractor used to read bank $0D for every room, so clones of
    Castle/GreatTree/Farm/... carried bank-$0D filler 'scripts' and boss
    rooms ($30, $34) failed to decode — caught by the all-rooms clone sweep."""
    return 0x0C if mid < 0x06 else 0x0D if mid < 0x20 else 0x0E if mid < 0x40 else 0x0F
ATTR_PTR_TABLE = 0x476F     # bank $17 (derive_room_palette.py, validated)
CUSTOM_ROOM_START = 0x6B


def _load_param_counts():
    """Opcode arity + branch-target index.

    S96: the source of truth is extracted/script_param_counts.json — the
    per-path COUNTER-INCREMENT count of every bank-$04 handler
    (tools/script_param_counts.py). It agrees with every handler/PyBoy-
    verified row (scriptgen OPS, the S92 $27/$21 overrides) and corrects 30
    rows of decompile_script.PARAM_COUNTS (e.g. $11 = 2 not 4, $37 = 1
    param and NOT a branch — its 'target' was the next op's bytes). Branch
    ops = handlers with a path into ScriptReturnProcess ($04:$7212); the
    target is the last parameter word read before it. The decompiler table
    is only a fallback when the JSON is missing."""
    path = os.path.join(ROOT, 'extracted', 'script_param_counts.json')
    pc, bt = {}, {}
    if os.path.exists(path):
        ops = json.load(open(path))['ops']
        for k, v in ops.items():
            code = int(k, 16)
            pc[code] = v['counts'][0]
            if 'branch' in v.get('ends', []) and v['counts'][0] > 0:
                bt[code] = v['counts'][0] - 1
    else:
        src = open(os.path.join(SCRIPT_DIR, 'decompile_script.py')).read()
        for m in re.finditer(r'0x([0-9A-Fa-f]{2}):(\d+)',
                             src.split('PARAM_COUNTS = {')[1].split('}')[0]):
            pc[int(m.group(1), 16)] = int(m.group(2))
        for m in re.finditer(r'0x([0-9A-Fa-f]{2}):\s*(\d+),',
                             src.split('BRANCH_TARGET_PARAM = {')[1].split('}')[0]):
            bt[int(m.group(1), 16)] = int(m.group(2))
        pc[0x27] = 0
        bt.pop(0x27, None)
        pc[0x21] = 1
    for name, (code, n) in SG.OPS.items():
        if pc.get(code, n) != n:
            raise SystemExit(f'scriptgen OPS {name} (${code:02X}) = {n} params but the '
                             f'handler analysis says {pc[code]} — fix one of them')
        pc[code] = n
    name_by_code = {code: name for name, (code, n) in SG.OPS.items()}
    name_by_code[0x27] = 'monster_party_op2'
    return pc, bt, name_by_code


def rb(rom, bank, addr):
    return rom[bank * 0x4000 + (addr - 0x4000)]


def rw(rom, bank, addr):
    return rb(rom, bank, addr) | (rb(rom, bank, addr + 1) << 8)


# --------------------------------------------------------------- scripts

def decode_script(rom, bank, start, pc, bt, stop_addrs):
    """Decode one script: linear + branch-reached blocks.

    Returns ordered [(addr, opcode, [params])] covering every reachable op,
    or raises with the suspect opcode on any segmentation failure.
    """
    ops = {}
    pend = [start]
    while pend:
        a = pend.pop()
        while a not in ops:
            w = rw(rom, bank, a)
            if w == 0xFFFF:
                ops[a] = (0x100, [])       # pseudo: end marker
                break
            if (w >> 8) != 0xFF:
                # bare word = text display ("say"): the engine consumes any
                # non-$FFxx word as a text id — exactly what the compiler's
                # ["text", id] emits (scriptgen: a naked `dw $id`).
                ops[a] = (0x101, [w])      # pseudo: say
                a += 2
                continue
            op = w & 0xFF
            if op not in pc:
                raise ValueError(f"${bank:02X}:{a:04X}: unknown opcode "
                                 f"${op:02X} (no param count)")
            n = pc[op]
            params = [rw(rom, bank, a + 2 + 2 * k) for k in range(n)]
            ops[a] = (op, params)
            if op in bt:
                tgt = params[bt[op]]
                if not (0x4000 <= tgt <= 0x7FFF):
                    raise ValueError(
                        f"${bank:02X}:{a:04X}: op ${op:02X} branch target "
                        f"${tgt:04X} outside the bank — param table wrong")
                pend.append(tgt)
            a += 2 + 2 * n
            if op in (0x14, 0x16):         # goto / return: no fall-through
                break
    # PROOF: every branch target is a decoded op boundary
    for a, (op, params) in ops.items():
        if op in bt and op != 0x100:
            tgt = params[bt[op]]
            if tgt not in ops:
                raise ValueError(
                    f"${bank:02X}:{a:04X}: op ${op:02X} branch target "
                    f"${tgt:04X} does not land on an op boundary — a param "
                    "count between them is wrong (fix the merged table)")
    return sorted(ops.items())


def ops_to_project(ordered, bt, name_by_code):
    """[(addr,(op,params))] → scriptgen op list with local @labels."""
    targets = set()
    for a, (op, params) in ordered:
        if op in bt and op != 0x100:
            targets.add(params[bt[op]])
    out = []
    for a, (op, params) in ordered:
        if a in targets:
            out.append(f"label:L{a:04X}")
        if op == 0x100:
            out.append(["end"])
            continue
        if op == 0x101:
            out.append(["text", f"0x{params[0]:04X}"])
            continue
        name = name_by_code.get(op, f"0x{op:02X}")
        row = ["op", name]
        for k, p in enumerate(params):
            if op in bt and k == bt[op]:
                row.append(f"@L{p:04X}")
            else:
                row.append(f"0x{p:04X}")
        out.append(row)
    return out


def flags_report(ordered):
    reads, writes, rams = set(), set(), set()
    for a, (op, params) in ordered:
        if op in (0x00, 0x01) and params:
            reads.add(params[0])
        elif op in (0x02, 0x03) and params:
            writes.add(params[0])
        elif op == 0x15 and params:
            rams.add(params[0])
    return reads, writes, rams


# --------------------------------------------------------------- room walk

def extract(source_mid, room_id, target_mid, step, project_dir):
    rom = open(ROM_PATH, 'rb').read()
    pc, bt, name_by_code = _load_param_counts()
    mt = json.load(open(MAP_TABLE))
    src = next(e for e in mt if e.get('map_type') == source_mid)

    # 1. record
    row = rom[0x26DD + source_mid * 8: 0x26DD + source_mid * 8 + 8]
    record = {"gfx_id": f"0x{row[0]:02X}", "gfx_bank": f"0x{row[1]:02X}",
              "width_px": row[2] | row[3] << 8,
              "height_px": row[4] | row[5] << 8,
              "collision_threshold": f"0x{row[6]:02X}"}

    # 2+4. screens + attrs (step 0 of each sub-room, raw-verified)
    layouts, screens = [], {}
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        'gam', os.path.join(SCRIPT_DIR, 'generate_attr_map.py'))
    gam = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(gam)
    # S96: index the room's bank-$17 screen table DIRECTLY by screen index
    # (row*4+col, the engine's own walk — ROOM_DATA_FORMAT / GATE_GENERATION
    # §7.1). generate_attr_map.parse_room_attr_entry only reads 8 screen
    # slots (the retired 4x2 assumption), so cloning GreatTree ($01, screens
    # up to 11) died with KeyError 8.
    def attr_step0(scr_idx):
        b17 = 0x17 * 0x4000
        tbl = rom[b17 + 0x476F - 0x4000 + source_mid * 2] | \
            (rom[b17 + 0x476F - 0x4000 + source_mid * 2 + 1] << 8)
        o = b17 + tbl - 0x4000 + scr_idx * 2
        ent = rom[o] | (rom[o + 1] << 8)
        if not (0x4000 <= ent < 0x8000):
            raise SystemExit(f"no attr row for screen {scr_idx}")
        row = b17 + ent - 0x4000 + 2 + min(step, 0) * 4
        return rom[row], rom[row + 1], rom[row + 2] | (rom[row + 3] << 8)
    used_scripts = set()
    for sr in src['sub_rooms']:
        scr_idx = sr['c925']
        st = sr['steps'][min(step, len(sr['steps']) - 1)]
        b01 = int(st['bytes_0_1'], 16)
        lay_entry, lay_bank = b01 & 0xFF, b01 >> 8
        npcs = []
        for it in st['interact_data']:
            raw = bytes(int(x, 16) for x in it['raw'].split())
            flat = int(it['entry_flat'], 16)
            if rom[flat:flat + 5] != raw:
                raise SystemExit(
                    f"RAW MISMATCH at {it['entry_flat']}: map_table.json says "
                    f"{raw.hex()} but ROM has {rom[flat:flat+5].hex()} — "
                    "regenerate the dump before cloning")
            if it.get('kind') == 'npc' and it.get('script_id', 255) != 255:
                used_scripts.add(it['script_id'])
            npcs.append({"kind": "raw",
                         "bytes": [f"0x{b:02X}" for b in raw],
                         "comment": f"{it.get('kind')} "
                                    f"({raw[2]},{raw[3]}) [vanilla verbatim]"})
        exits = []
        for ex in st['exit_data']:
            raw = bytes(int(x, 16) for x in ex['raw'].split())
            flat = int(ex['entry_flat'], 16)
            if rom[flat:flat + 7] != raw:
                raise SystemExit(f"RAW MISMATCH exit at {ex['entry_flat']}")
            exits.append({
                "x": raw[0], "y": raw[1], "dest": f"vanilla:${raw[2]:02X}",
                "gate_flag": raw[3], "screen_byte": f"0x{raw[4]:02X}",
                "spawn_x": raw[5], "spawn_y": raw[6],
                "comment": f"vanilla exit -> map ${raw[2]:02X} [verbatim]"})
        # attr → custom.layouts attr-only item
        aidx, abank, _pal = attr_step0(scr_idx)
        res = gam.decompress_lz(rom, abank, aidx)
        if res is None or len(res[0]) != 256:
            raise SystemExit(f"attr decompress failed screen {scr_idx}")
        lid = f"{room_id}_attr_s{scr_idx}"
        layouts.append({"id": lid,
                        "comment": f"vanilla ${source_mid:02X} screen "
                                   f"{scr_idx} attr (bank ${abank:02X} "
                                   f"entry ${aidx:02X}, re-emitted)",
                        "attr": LAY.unpack_attr(res[0])})
        screens[str(scr_idx)] = {
            "layout": {"bank": f"0x{lay_bank:02X}",
                       "entry": f"0x{lay_entry:02X}"},
            # S94: per-screen attr map (CustomAttrCheck reads one entry per
            # screen; the S92 base+2 stride is gone)
            "attr": {"id": lid},
            "step_counter": "auto", "npcs": npcs, "exits": exits}

    # 5. palette (derive_room_palette logic, validated 30/30)
    spec2 = importlib.util.spec_from_file_location(
        'drp', os.path.join(SCRIPT_DIR, 'derive_room_palette.py'))
    drp = importlib.util.module_from_spec(spec2)
    spec2.loader.exec_module(drp)
    ptr = drp.normal_room_pal_ptr(rom, source_mid)
    env = drp._read_palettes(rom, ptr, 4, force=True)
    pal_rows = [list(p) for p in env]
    # slots 4-7: the loader only ever loads slots 0-3 for custom rooms
    # (KEY_LESSONS S8 / CustomPalCheck b=$04 c=$00), so rows 4-7 are dead
    # data — copy them from an existing proven project palette for layout
    # parity, else zero-fill.
    donor = None
    try:
        pjd = json.load(open(os.path.join(project_dir, 'project.json')))
        donor = (pjd['custom'].get('palettes') or [None])[0]
    except Exception:
        pass
    if donor and len(donor.get('colors_rgb555', [])) == 8:
        pal_rows += [list(r) for r in donor['colors_rgb555'][4:]]
    else:
        pal_rows += [[0, 0, 0, 0]] * 4
    palette = {"id": f"pal_{room_id}", "label": f"CustomPaletteColors_{room_id}",
               "placement": "b",
               "colors_rgb555": pal_rows,
               "comment": [f"derived from vanilla ${source_mid:02X} "
                           "(derive_room_palette logic; idx1/idx3 forced)"]}

    # 6. scripts
    SCRIPT_BANK = script_bank(source_mid)
    tbl = rw(rom, SCRIPT_BANK, SCRIPT_TBL + source_mid * 2)
    # the per-map pointer lists are packed back to back: this map's list ends
    # where the next map's list (any other master-table row) begins
    lo, hi = {0x0C: (0, 6), 0x0D: (6, 0x20), 0x0E: (0x20, 0x40),
              0x0F: (0x40, 0x6B)}[SCRIPT_BANK]
    starts = {rw(rom, SCRIPT_BANK, SCRIPT_TBL + m * 2) for m in range(lo, hi)}
    nxt = min([x for x in starts if x > tbl] + [0x8000])
    ptrs, a = [], tbl
    while len(ptrs) < 100 and a < nxt:
        p = rw(rom, SCRIPT_BANK, a)
        if not (0x4000 <= p <= 0x7FFF):
            break
        ptrs.append(p)
        a += 2
    heads = set(ptrs)
    scripts, script_map, ext_report = [], {}, []
    for idx, p in enumerate(ptrs):
        ordered = decode_script(rom, SCRIPT_BANK, p, pc, bt, heads - {p})
        sid = f"{room_id}_scr{idx:02d}"
        scripts.append({"id": sid,
                        "_source": f"${SCRIPT_BANK:02X}:{p:04X} "
                                   f"(vanilla map ${source_mid:02X} scr{idx})",
                        "ops": ops_to_project(ordered, bt, name_by_code)})
        script_map[str(idx)] = sid
        fr, fw, rams = flags_report(ordered)
        ext_report.append((idx, sorted(fr), sorted(fw), sorted(rams)))

    room = {"id": room_id, "mapID": f"0x{target_mid:02X}",
            "source_mapID": f"0x{source_mid:02X}",
            "_cloned_from": f"vanilla ${source_mid:02X} step {step} "
                            "(extract_room.py S92)",
            "record": record,
            "render": {"palette": f"pal_{room_id}",
                       "attr": {"id": f"{room_id}_attr_s0"}},
            "screens": screens,
            "scripts": script_map}
    # 7. music: vanilla derivation result for the source room
    bgm = vanilla_room_bgm(rom, source_mid)
    music_default = {f"0x{target_mid:02X}": f"0x{bgm:02X}"} if bgm else {}
    return room, layouts, palette, scripts, music_default, ext_report


def vanilla_room_bgm(rom, mid):
    """RoomBGMTable value for a vanilla mapID (SOUND_SYSTEM §8).

    Parsed from patches/bank_001.asm's RoomBGMTable db rows (the S64
    rewrite preserved the vanilla table verbatim; footprint note at the
    label). mapID $06 -> $1E, the Arena theme."""
    src = open(os.path.join(ROOT, 'patches', 'bank_001.asm')).read()
    body = src.split('RoomBGMTable:', 2)[-1]
    vals = []
    for line in body.splitlines():
        line = line.strip()
        if line.startswith('db '):
            vals += [int(t, 16) for t in
                     re.findall(r'\$([0-9A-Fa-f]{2})', line.split(';')[0])]
        elif vals:
            break
    return vals[mid] if mid < len(vals) else 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--source', help='vanilla mapID to clone, e.g. 0x06')
    ap.add_argument('--source-custom', help='custom room id to copy')
    ap.add_argument('--room-id', required=True)
    ap.add_argument('--project', required=True)
    ap.add_argument('--mapID', help='target mapID (default: next dense)')
    ap.add_argument('--step', type=int, default=0,
                    help='which step/state to capture (default 0)')
    ap.add_argument('--apply', action='store_true',
                    help='merge into the project.json (default: print)')
    args = ap.parse_args()

    pj = os.path.join(args.project, 'project.json')
    prj = json.load(open(pj))
    rooms = prj['custom']['rooms']
    used = [int(str(r['mapID']), 16) for r in rooms]
    target = int(str(args.mapID), 16) if args.mapID else max(used) + 1

    if args.source_custom:
        srcroom = next(r for r in rooms if r['id'] == args.source_custom)
        room = copy.deepcopy(srcroom)
        room['id'] = args.room_id
        room['mapID'] = f"0x{target:02X}"
        room.pop('_cloned_from', None)
        room['_cloned_from'] = f"custom room {args.source_custom} " \
                               "(extract_room.py S92 custom→custom)"
        # scripts are shared by id — a custom→custom clone reuses them
        add = ([room], [], None, [], {}, [])
    else:
        src_mid = int(str(args.source), 16)
        room, layouts, palette, scripts, music, rep = extract(
            src_mid, args.room_id, target, args.step, args.project)
        add = ([room], layouts, palette, scripts, music, rep)

    room_l, layouts, palette, scripts, music, rep = add
    if args.apply:
        rooms.extend(room_l)
        prj['custom'].setdefault('layouts', []).extend(layouts)
        if palette:
            prj['custom'].setdefault('palettes', []).append(palette)
        prj['custom'].setdefault('scripts', []).extend(scripts)
        if music:
            prj['custom'].setdefault('music', {}) \
                         .setdefault('room_defaults', {}).update(music)
        json.dump(prj, open(pj, 'w'), indent=1)
        print(f"merged into {pj}: room {args.room_id} at 0x{target:02X}")
    else:
        print(json.dumps({"room": room_l, "layouts": layouts,
                          "palette": palette, "scripts": scripts,
                          "music_room_defaults": music}, indent=1))
    for idx, fr, fw, rams in rep:
        print(f"; scr{idx:02d} flags read {list(map(hex, fr))} "
              f"write {list(map(hex, fw))} cond-RAM {list(map(hex, rams))}",
              file=sys.stderr)
    if rep:
        print("; ^ ORPHANED-TRIGGER LIST (EDITOR_DESIGN §6.1): each vanilla "
              "story flag/RAM read must be satisfied or stripped in the "
              "clone", file=sys.stderr)


if __name__ == '__main__':
    main()
