# DWM1 Complete Gate Reference
# Source: Game FAQ, verified against gameplay
# Internal gate ID → Gate name mapping verified via encounter pool cross-reference
#
# Format: gate_id, name, floors, boss_species, boss_name, boss_recruitable

GATES = {
    0:  {"name": "Gate of Beginning",     "floors": 5,  "boss": "Healer",    "boss_name": "Hale",  "recruitable": True,  "auto_join": True},
    1:  {"name": "Gate of Villager",      "floors": 5,  "boss": "Dragon",    "boss_name": "Dran",  "recruitable": True,  "auto_join": True},
    2:  {"name": "Gate of Talisman",      "floors": 6,  "boss": "Golem",     "boss_name": "Golm",  "recruitable": True,  "auto_join": True},
    3:  {"name": "Gate of Memories",      "floors": 5,  "boss": "MadCat",    "boss_name": "Gig",   "recruitable": True,  "auto_join": True},
    4:  {"name": "Gate of Bewilder",      "floors": 6,  "boss": "FaceTree",  "boss_name": "Face",  "recruitable": True,  "auto_join": True},
    5:  {"name": "Bazaar Gate",           "floors": 9,  "boss": "MadKnight", "boss_name": "Pash",  "recruitable": True,  "auto_join": True},
    6:  {"name": "Gate of Peace",         "floors": 8,  "boss": "FangSlime", "boss_name": "Fang",  "recruitable": True,  "auto_join": True},
    7:  {"name": "Gate of Bravery",       "floors": 9,  "boss": "BigEye",    "boss_name": None,    "recruitable": False, "auto_join": False},
    8:  {"name": "Well Gate",             "floors": 12, "boss": "Gigantes",  "boss_name": "Gant",  "recruitable": True,  "auto_join": False},
    9:  {"name": "Gate of Strength",      "floors": 11, "boss": "StoneMan",  "boss_name": None,    "recruitable": False, "auto_join": False},
    10: {"name": "Gate of Anger",         "floors": 11, "boss": "BattleRex", "boss_name": "Wrex",  "recruitable": True,  "auto_join": True},
    11: {"name": "Farm Gate",             "floors": 12, "boss": "Copycat",   "boss_name": "Mime",  "recruitable": True,  "auto_join": True},
    12: {"name": "Arena - Left Gate",     "floors": 16, "boss": "Digster",   "boss_name": "Ebi",   "recruitable": True,  "auto_join": True},
    13: {"name": "Gate of Joy",           "floors": 14, "boss": "FunkyBird", "boss_name": "Func",  "recruitable": True,  "auto_join": True},
    14: {"name": "Gate of Wisdom",        "floors": 15, "boss": "SkyDragon", "boss_name": None,    "recruitable": False, "auto_join": False},
    15: {"name": "Medal Gate",            "floors": 16, "boss": "KingSlime", "boss_name": "Kix",   "recruitable": True,  "auto_join": False},
    16: {"name": "Gate of Happiness",     "floors": 18, "boss": "Jamirus",   "boss_name": None,    "recruitable": False, "auto_join": False},
    17: {"name": "Gate of Temptation",    "floors": 20, "boss": "Servant",   "boss_name": "Mats",  "recruitable": True,  "auto_join": False},
    18: {"name": "Gate of Labyrinth",     "floors": 23, "boss": "DarkHorn",  "boss_name": "Dark",  "recruitable": True,  "auto_join": False},
    19: {"name": "Gate of Judgement",     "floors": 25, "boss": "Akubar",    "boss_name": None,    "recruitable": False, "auto_join": False},
    20: {"name": "Library Gate",          "floors": 25, "boss": "Orochi",    "boss_name": None,    "recruitable": False, "auto_join": False},
    21: {"name": "Gate of Reflection",    "floors": 29, "boss": "Durran",    "boss_name": None,    "recruitable": False, "auto_join": False},
    22: {"name": "Gate of Ambition",      "floors": 30, "boss": "DracoLord",  "boss_name": None,   "recruitable": False, "auto_join": False},
    23: {"name": "Gate of Demolition",    "floors": 29, "boss": "Hargon/Sidoh", "boss_name": None, "recruitable": False, "auto_join": False},
    24: {"name": "Gate of Mastermind",    "floors": 28, "boss": "Baramos",   "boss_name": None,    "recruitable": False, "auto_join": False},
    25: {"name": "Gate of Control",       "floors": 30, "boss": "Zoma",      "boss_name": None,    "recruitable": False, "auto_join": False},
    26: {"name": "Gate of Extinction",    "floors": 30, "boss": "Pizzaro",   "boss_name": None,    "recruitable": False, "auto_join": False},
    27: {"name": "Gate of Sleep",         "floors": 30, "boss": "Esterk",    "boss_name": None,    "recruitable": False, "auto_join": False},
    28: {"name": "Bazaar Edge Gate",      "floors": 30, "boss": "Mirudraas", "boss_name": None,    "recruitable": False, "auto_join": False},
    29: {"name": "Arena - Right Gate",    "floors": 27, "boss": "Mudou",     "boss_name": None,    "recruitable": False, "auto_join": False},
    30: {"name": "Old Man's Gate",        "floors": 30, "boss": "DeathMore", "boss_name": None,    "recruitable": False, "auto_join": False},
    31: {"name": "Unused Gate",           "floors": 99, "boss": None,        "boss_name": None,    "recruitable": False, "auto_join": False},
}

# Gate encounter monsters (from FAQ, for verification against ROM dump)
# Format: {gate_id: {monster_name: floor_range_string}}
GATE_MONSTERS = {
    0:  {"Slime": "1-4", "Dracky": "1-4", "Anteater": "1-4"},
    1:  {"Anteater": "1-2", "Picky": "1-2", "GoHopper": "1-4", "Stubsuck": "1-4", "Gremlin": "3-4", "PillowRat": "3-4"},
    2:  {"Anteater": "1-2", "MiniDrak": "1-2", "ArmyAnt": "1-5", "Spooky": "1-5", "Goopi": "3-5", "Picky": "3-5"},
    3:  {"DragonKid": "1-2", "Goopi": "1-2", "PillowRat": "1-2", "Catapilla": "1-4", "FairyRat": "3-4", "Picky": "3-4", "SpotSlime": "3-4"},
    4:  {"BigRoost": "1-2", "DragonKid": "1-2", "MiniDrak": "1-2", "SpotSlime": "1-5", "Demonite": "3-5", "EvilSeed": "3-5", "Hork": "3-5"},
    5:  {"Crestpent": "1-3", "FairyRat": "1-3", "SpotSlime": "1-3", "BigRoost": "1-5", "BeanMan": "4-5", "DragonKid": "4-5", "Catapilla": "4-8", "1EyeClown": "6-8", "Demonite": "6-8", "Hork": "6-8"},
    6:  {"BigRoost": "1-3", "CoilBird": "1-3", "SpotSlime": "1-3", "Crestpent": "1-7", "BoneSlave": "4-5", "DragonKid": "4-5", "Almiraj": "4-7", "BullBird": "6-7", "Hork": "6-7"},
    7:  {"Demonite": "1-3", "1EyeClown": "1-3", "BeanMan": "1-8", "FloraMan": "1-8", "SabreMan": "4-5", "GiantWorm": "4-8", "BullBird": "6-8"},
    8:  {"GiantSlug": "1-5", "FloraMan": "1-11", "TreeSlime": "4-5", "GiantWorm": "6-8", "BullBird": "6-11", "MudDoll": "6-11", "Metaly": "9-11", "SabreMan": "9-11"},
    9:  {"MudDoll": "1-5", "TreeSlime": "1-3,6-10", "SkulRider": "1-8", "FairyDrak": "1-5,9-10", "WingTree": "4-10", "DrakSlime": "6-10"},
    10: {"GiantWorm": "1-3", "GiantSlug": "1-5", "Poisongon": "1-8", "CatFly": "1-10", "Eyeder": "4-10", "Putrepup": "6-10", "DrakSlime": "9-10"},
    11: {"Butterfly": "1-3", "FairyDrak": "1-5", "MadRaven": "1-8", "Skullroo": "1-11", "Mudron": "4-5,9-11", "DrakSlime": "6-11", "Facer": "6-11"},
    12: {"WingSlime": "1-5", "MedusaEye": "1-6", "MadCandle": "1-12", "MadGopher": "1-15", "Slabbit": "6-15", "WindBeast": "9-15", "Gasgon": "13-15"},
    13: {"Snaily": "1-5", "Gulpple": "1-8", "Saccer": "1-12", "MadPecker": "1-8,13", "EyeBall": "6-13", "Babble": "9-13", "Mummy": "9-13"},
    14: {"Facer": "1-5", "Tonguella": "1-14", "FloraJay": "1-14", "Pteranod": "1-14", "Armorpede": "6-14"},
    15: {"Gismo": "1-8", "NiteWhip": "1-8", "BoxSlime": "1-18", "Orc": "1-18", "Reaper": "6-18", "RogueNite": "6-18"},
    16: {"Gasgon": "1-4", "Oniono": "1-12", "Pixy": "1-16", "Gophecada": "1-17", "DeadNite": "5-17", "StubBird": "13-17", "SpikeyBoy": "17"},
    17: {"SpikeyBoy": "1-8", "Mommonja": "1-12", "KingCobra": "1-16", "SlimeNite": "1-19", "StagBug": "9-19", "MistyWing": "13-19", "DarkEye": "17-19"},
    18: {"Chamelgon": "1-5", "CactiBall": "1-15", "TailEater": "1-10,16-20", "RockSlime": "1-22", "Gismo": "1-22", "DuckKite": "6-22", "AgDevil": "6-22", "WindMerge": "21-22"},
    19: {"WeedBug": "1-5", "TreeBoy": "1-20", "HammerMan": "1-24", "MadGoose": "1-10,21-24", "SpotKing": "1-24", "Droll": "6-15", "LizardFly": "11-24", "GiantMoth": "16-24"},
    20: {"AmberWeed": "1-5", "CurseLamp": "1-10", "ArmyCrab": "1-20", "ArcDemon": "1-24", "MadSpirit": "1-10,16-24", "WildApe": "6-24", "Tortragon": "11-24", "LandOwl": "21-24"},
    21: {"EvilWand": "1-5", "EvilBeast": "1-10", "Shadow": "1-10", "SlimeBorg": "1-15", "LizardMan": "1-20", "Grizzly": "6-28", "FireWeed": "11-25", "Wyvern": "11-25", "MadHornet": "16-28", "Lionex": "16-28", "RotRaven": "21-28", "JewelBag": "26-28"},
    22: {"ArmyAnt": "1-5", "Catapilla": "1-5", "GiantWorm": "1-5", "GoHopper": "1-5", "Armorpede": "6-10", "Butterfly": "6-10", "Eyeder": "6-10", "GiantSlug": "6-10", "Gophecada": "11-20", "StagBug": "11-20", "TailEater": "11-20", "WeedBug": "11-20", "ArmyCrab": "21-29", "Droll": "21-29", "GiantMoth": "21-29", "MadHornet": "21-29"},
    23: {"BeanMan": "1-5", "EvilSeed": "1-5", "FloraMan": "1-5", "Stubsuck": "1-5", "Gulpple": "6-10", "MadPlant": "6-10", "Oniono": "6-10", "WingTree": "6-10", "AmberWeed": "11-20", "CactiBall": "11-20", "TreeBoy": "11-20", "FireWeed": "11-20", "DanceVegi": "21-28", "ManEater": "21-28", "Snapper": "21-28"},
    24: {"BigRoost": "1-5", "BullBird": "1-5", "Dracky": "1-5", "Picky": "1-5", "FloraJay": "6-10", "MadPecker": "6-10", "MadRaven": "6-10", "StubBird": "6-10", "DuckKite": "11-20", "LandOwl": "11-20", "MadGoose": "11-20", "MistyWing": "11-20", "MadCondor": "21-26", "WhipBird": "21-26", "Wyvern": "21-26", "ZapBird": "21-26"},
    25: {"Metaly": "1-5", "Slime": "1-5", "SpotSlime": "1-5", "TreeSlime": "1-5", "Babble": "6-10", "DrakSlime": "6-10", "Snaily": "6-10", "WingSlime": "6-10", "BoxSlime": "11-20", "RockSlime": "11-20", "Slabbit": "11-20", "SlimeNite": "11-20", "Metabble": "21-29", "SlimeBorg": "21-29", "SpotKing": "21-29"},
    26: {"1EyeClown": "1-5", "Demonite": "1-5", "Gremlin": "1-5", "SkulRider": "1-5", "DarkEye": "6-10", "EyeBall": "6-10", "MedusaEye": "6-10", "Pixy": "6-10", "AgDevil": "11-20", "ArcDemon": "11-20", "EvilBeast": "11-20", "Orc": "11-20", "GoatHorn": "21-29", "Grendal": "21-29", "Lionex": "21-29", "Ogre": "21-29"},
    27: {"BoneSlave": "1-5", "Hork": "1-5", "Putrepup": "1-5", "Spooky": "1-5", "DeadNite": "6-10", "Mudron": "6-10", "Mummy": "6-10", "NiteWhip": "6-10", "MadSpirit": "11-20", "Reaper": "11-20", "Shadow": "11-20", "WindMerge": "11-20", "DarkCrab": "21-29", "DeadNoble": "21-29", "RotRaven": "21-29", "Skeletor": "21-29", "Skullgon": "21-29"},
    28: {"CoilBird": "1-5", "Goopi": "1-5", "MudDoll": "1-5", "SabreMan": "1-5", "Facer": "6-10", "MadCandle": "6-10", "RogueNite": "6-10", "SpikyBoy": "6-10", "CurseLamp": "11-20", "EvilWand": "11-20", "Gismo": "11-20", "JewelBag": "11-20", "Balzak": "21-29", "BombCrag": "21-29", "MetalDrak": "21-26", "Roboster": "21-26"},
    29: {"Almiraj": "1-5", "CatFly": "1-5", "FairyRat": "1-5", "PillowRat": "1-5", "Skullroo": "1-5", "MadGopher": "6-10", "Mommonja": "6-10", "Saccer": "6-10", "Tonguella": "6-10", "WindBeast": "6-10", "Goategon": "11-20", "Grizzly": "11-20", "HammerMan": "21-29", "SuperTen": "21-29", "WildApe": "21-29", "GulpBeast": "21-29", "IronTurt": "21-26", "Trumpeter": "21-26", "Unicorn": "21-26", "Yeti": "21-26"},
    30: {"Crestpent": "1-5", "DragonKid": "1-5", "MiniDrak": "1-5", "Poisongon": "1-5", "Chamelgon": "6-10", "FairyDrak": "6-10", "Gasgon": "6-10", "KingCobra": "6-10", "Pteranod": "6-10", "LizardFly": "11-20", "LizardMan": "11-20", "Swordgon": "11-20", "Tortragon": "11-20", "WingSnake": "11-20", "Andreal": "21-29", "GreatDrak": "21-29", "MadDragon": "21-29", "Rayburn": "21-29", "Spikerous": "21-29"},
    31: {"boss": None, "note": "Unused gate, 99 floors, empty boss room"},
}
