#!/usr/bin/env python3
"""Generate GBC palette attribute data for DWM1 custom room layouts.

The GBC BG attribute map assigns a palette (0-7) to each tile position.
In vanilla rooms, this data is stored compressed in bank $3C/$3D, indexed
by attr_idx from bank $17's per-room/per-screen step entries.

Format (256 bytes decompressed):
  8 rows × 32 bytes. Each row covers 2 tile rows (even + odd).
  Each 32-byte row: [10 bytes for even row][6 padding][10 bytes for odd row][6 padding]
  Each byte is nibble-packed: high nibble = left tile's palette, low nibble = right tile's palette.

This tool:
  1. Builds a tile→palette mapping from vanilla rooms using a given tileset
  2. Generates the 256-byte attr map for a custom layout
  3. LZSS compresses it
  4. Outputs ASM db statements for bank $64

Usage:
  python3 generate_attr_map.py layout.json                 # generate for Farm tileset
  python3 generate_attr_map.py layout.json --tileset 29:01 # explicit tileset
  python3 generate_attr_map.py --dump-mapping 29:01        # show tile→palette map
  python3 generate_attr_map.py --all-tilesets               # dump all tileset mappings

Generated by: tools/generate_attr_map.py
"""
import json, os, sys, argparse, re

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.join(SCRIPT_DIR, '..')
ROM_PATH = os.path.join(ROOT_DIR, 'data', 'DWM-original.gbc')

sys.path.insert(0, ROOT_DIR)
from tools.compress_tiles import compress_lz
from tools.decompress_tiles import decompress_lz


# ---------------------------------------------------------------------------
# ROM data extraction
# ---------------------------------------------------------------------------

def read_rom():
    with open(ROM_PATH, 'rb') as f:
        return f.read()


def get_attr_ptr_table(rom):
    """Read the AttrPtrTable from bank $17 ($476F): 107 entries × 2 bytes."""
    base = 0x17 * 0x4000
    table_addr = 0x476F
    entries = []
    for i in range(107):  # mapIDs 0-106 ($00-$6A)
        off = base + table_addr - 0x4000 + i * 2
        ptr = rom[off] | (rom[off + 1] << 8)
        entries.append(ptr)
    return entries


def parse_room_attr_entry(rom, ptr):
    """Parse a room's attribute screen table and step entries from bank $17.
    
    Returns: dict mapping screen_index → list of (attr_idx, attr_bank, pal_ptr) per step
    """
    base = 0x17 * 0x4000
    off = base + ptr - 0x4000
    
    # Read screen pointers until we detect data section
    # Screen table: pairs of 2-byte pointers, $FFFF = unused screen
    # We read up to 8 screen slots (max screens per room)
    screen_ptrs = []
    for i in range(8):
        p = rom[off + i * 2] | (rom[off + i * 2 + 1] << 8)
        screen_ptrs.append(p)
    
    result = {}
    for scr_idx, scr_ptr in enumerate(screen_ptrs):
        if scr_ptr == 0xFFFF:
            continue
        
        scr_off = base + scr_ptr - 0x4000
        # Format: [wram_addr:2] then [attr_idx:1, attr_bank:1, pal_ptr:2] × N steps
        wram = rom[scr_off] | (rom[scr_off + 1] << 8)
        if not (0xD900 <= wram <= 0xD9FF):
            continue
        
        steps = []
        pos = scr_off + 2
        for step_num in range(10):  # max steps
            attr_idx = rom[pos]
            attr_bank = rom[pos + 1]
            pal_lo = rom[pos + 2]
            pal_hi = rom[pos + 3]
            
            # Validity check: attr_bank should be in tileset range
            if attr_bank < 0x20 or attr_bank > 0x50:
                # Check if this looks like next screen's WRAM address
                maybe_wram = attr_idx | (attr_bank << 8)
                if 0xD900 <= maybe_wram <= 0xD9FF:
                    break
                break
            
            pal_ptr = pal_lo | (pal_hi << 8)
            steps.append((attr_idx, attr_bank, pal_ptr))
            pos += 4
        
        if steps:
            result[scr_idx] = steps
    
    return result


# ---------------------------------------------------------------------------
# Editor room extraction
# ---------------------------------------------------------------------------

def load_editor_rooms():
    """Extract room data from the HTML tile editor."""
    editor_path = os.path.join(ROOT_DIR, 'towards_editor', 'DWM1_Tile_Editor.html')
    if not os.path.exists(editor_path):
        return {}
    
    with open(editor_path) as f:
        html = f.read()
    
    rooms = {}
    # Find all room entries like "4_0":{...}
    pattern = re.compile(r'"(\d+_\d+)"\s*:\s*\{')
    for m in pattern.finditer(html):
        key = m.group(1)
        start = m.end() - 1  # opening brace
        depth = 0
        for i in range(start, min(start + 10000, len(html))):
            if html[i] == '{':
                depth += 1
            elif html[i] == '}':
                depth -= 1
            if depth == 0:
                try:
                    room = json.loads(html[start:i + 1])
                    rooms[key] = room
                except json.JSONDecodeError:
                    pass
                break
    
    return rooms


# ---------------------------------------------------------------------------
# Tile → Palette mapping
# ---------------------------------------------------------------------------

def build_tile_palette_map(rom, tileset_key):
    """Build a tile_index → palette_number mapping for a given tileset.
    
    Analyzes all vanilla rooms that use this tileset by cross-referencing
    editor room data (for layouts + tileset assignments) with ROM attr data.
    
    Args:
        rom: full ROM bytes
        tileset_key: "bank:step" like "29:01" (Farm tileset)
    
    Returns:
        dict mapping tile_index (0-255) → palette_number (0-7)
    """
    rooms = load_editor_rooms()
    attr_table = get_attr_ptr_table(rom)
    
    tile_pal = {}
    conflicts = []
    sources = []
    
    for room_key, room in rooms.items():
        if room.get('ts') != tileset_key:
            continue
        
        mapid = room['mapid']
        scr = room['scr']
        layout = room['layout']
        
        if mapid >= len(attr_table):
            continue
        
        # Get attr data for this room/screen
        room_attr_ptr = attr_table[mapid]
        if room_attr_ptr == 0xFFFF:
            continue
        
        screen_steps = parse_room_attr_entry(rom, room_attr_ptr)
        if scr not in screen_steps:
            continue
        
        # Use step 0's attr data
        attr_idx, attr_bank, pal_ptr = screen_steps[scr][0]
        
        result = decompress_lz(rom, attr_bank, attr_idx)
        if not result or len(result[0]) != 256:
            continue
        
        attr_data = result[0]
        
        # Extract tile→palette pairs
        screen_count = 0
        for attr_row in range(8):
            for half in range(2):
                tile_row = attr_row * 2 + half
                base = attr_row * 32 + half * 16
                for col_pair in range(10):
                    byte_val = attr_data[base + col_pair]
                    left_pal = (byte_val >> 4) & 0xF
                    right_pal = byte_val & 0xF
                    
                    left_tile = layout[tile_row][col_pair * 2]
                    right_tile = layout[tile_row][col_pair * 2 + 1]
                    
                    for tile, pal in [(left_tile, left_pal), (right_tile, right_pal)]:
                        if tile in tile_pal:
                            if tile_pal[tile] != pal:
                                conflicts.append(
                                    f'Tile 0x{tile:02X}: pal {tile_pal[tile]} vs {pal} '
                                    f'(room {room_key})')
                        else:
                            tile_pal[tile] = pal
                            screen_count += 1
        
        sources.append(f'{room_key} ({room.get("name", "?")}): +{screen_count} tiles')
    
    if conflicts:
        print(f'WARNING: {len(conflicts)} palette conflicts:', file=sys.stderr)
        for c in conflicts[:10]:
            print(f'  {c}', file=sys.stderr)
    
    return tile_pal, sources


def generate_attr_data(layout_20x16, tile_pal, default_pal=0):
    """Generate the 256-byte attribute map for a custom layout.
    
    Args:
        layout_20x16: list of 16 rows, each 20 tile indices
        tile_pal: dict mapping tile_index → palette_number
        default_pal: palette for unmapped tiles (default 0)
    
    Returns:
        bytes: 256-byte attribute map in game format
    """
    output = bytearray(256)
    unmapped = set()
    
    for attr_row in range(8):
        for half in range(2):
            tile_row = attr_row * 2 + half
            base = attr_row * 32 + half * 16
            
            for col_pair in range(10):
                left_col = col_pair * 2
                right_col = col_pair * 2 + 1
                
                left_tile = layout_20x16[tile_row][left_col]
                right_tile = layout_20x16[tile_row][right_col]
                
                left_pal = tile_pal.get(left_tile, default_pal)
                right_pal = tile_pal.get(right_tile, default_pal)
                
                if left_tile not in tile_pal:
                    unmapped.add(left_tile)
                if right_tile not in tile_pal:
                    unmapped.add(right_tile)
                
                output[base + col_pair] = (left_pal << 4) | right_pal
            
            # Padding bytes 10-15 stay as 0x00
    
    if unmapped:
        print(f'WARNING: {len(unmapped)} tiles without palette mapping '
              f'(using default {default_pal}): {sorted(unmapped)}', file=sys.stderr)
    
    return bytes(output)


def format_asm_db(data, label, bytes_per_line=16):
    """Format compressed data as ASM db statements."""
    lines = [f'; {label}: {len(data)} bytes compressed (256 decompressed)']
    lines.append(f'{label}:')
    for i in range(0, len(data), bytes_per_line):
        chunk = data[i:i + bytes_per_line]
        hex_bytes = ', '.join(f'${b:02X}' for b in chunk)
        lines.append(f'    db {hex_bytes}')
    return '\n'.join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description='Generate GBC palette attribute data')
    parser.add_argument('layout_json', nargs='?', help='Custom layout JSON file (20×16 grid)')
    parser.add_argument('--tileset', default='29:01',
                        help='Tileset key "bank:step" (default: 29:01 = Farm)')
    parser.add_argument('--label', default='CustomAttr_Room6B',
                        help='ASM label for the compressed data')
    parser.add_argument('--dump-mapping', metavar='TS',
                        help='Dump tile→palette map for a tileset and exit')
    parser.add_argument('--verify', action='store_true',
                        help='Verify roundtrip decompression')
    parser.add_argument('-o', '--output', help='Output file (default: stdout)')
    args = parser.parse_args()
    
    rom = read_rom()
    
    if args.dump_mapping:
        tile_pal, sources = build_tile_palette_map(rom, args.dump_mapping)
        print(f'Tileset {args.dump_mapping}: {len(tile_pal)} tiles mapped from {len(sources)} screens')
        for s in sources:
            print(f'  {s}')
        print(f'\nTile → Palette:')
        for t in sorted(tile_pal.keys()):
            print(f'  0x{t:02X} ({t:3d}) → palette {tile_pal[t]}')
        return
    
    if not args.layout_json:
        parser.error('layout_json required (or use --dump-mapping)')
    
    # Load custom layout
    with open(args.layout_json) as f:
        data = json.load(f)
    
    # Handle both raw array and {layout: ...} wrapper
    if isinstance(data, dict):
        layout = data.get('layout', data)
    else:
        layout = data
    
    if len(layout) != 16 or any(len(r) != 20 for r in layout):
        print(f'ERROR: Layout must be 20×16, got {len(layout[0])}×{len(layout)}',
              file=sys.stderr)
        sys.exit(1)
    
    # Build tile→palette mapping
    tile_pal, sources = build_tile_palette_map(rom, args.tileset)
    print(f'Tileset {args.tileset}: {len(tile_pal)} tile→palette mappings '
          f'from {len(sources)} screens', file=sys.stderr)
    
    # Generate attr data
    attr_raw = generate_attr_data(layout, tile_pal)
    print(f'Generated 256-byte attr map', file=sys.stderr)
    
    # Compress
    compressed = compress_lz(attr_raw)
    print(f'Compressed: {len(compressed)} bytes '
          f'({len(compressed)/256*100:.0f}% of original)', file=sys.stderr)
    
    # Verify roundtrip
    if args.verify:
        # Write temp data to verify decompression
        marker = compressed[2]
        out_len = compressed[0] | (compressed[1] << 8)
        # Use our own decompressor
        decompressed = _decompress_verify(compressed)
        if decompressed == attr_raw:
            print('Roundtrip verification: PASS', file=sys.stderr)
        else:
            print('Roundtrip verification: FAIL', file=sys.stderr)
            diffs = sum(1 for a, b in zip(decompressed, attr_raw) if a != b)
            print(f'  {diffs} byte differences', file=sys.stderr)
    
    # Output
    asm = format_asm_db(compressed, args.label)
    if args.output:
        with open(args.output, 'w') as f:
            f.write(asm + '\n')
        print(f'Written to {args.output}', file=sys.stderr)
    else:
        print(asm)


def _decompress_verify(compressed):
    """Simple LZSS decompressor for roundtrip verification."""
    out_len = compressed[0] | (compressed[1] << 8)
    marker = compressed[2]
    src = 3
    output = bytearray(out_len)
    out_pos = 0
    
    while out_pos < out_len and src < len(compressed):
        b = compressed[src]
        src += 1
        
        if b != marker:
            output[out_pos] = b
            out_pos += 1
        else:
            if src + 1 >= len(compressed):
                break
            offset_lo = compressed[src]
            src += 1
            control = compressed[src]
            src += 1
            
            offset_hi = (control >> 4) & 0x0F
            copy_len_code = control & 0x0F
            
            offset = offset_lo | (offset_hi << 8)
            
            if copy_len_code == 0x0F:
                if src >= len(compressed):
                    break
                copy_len = compressed[src] + 19
                src += 1
            else:
                copy_len = copy_len_code + 4
            
            for j in range(copy_len):
                if offset + j < len(output) and out_pos < out_len:
                    output[out_pos] = output[offset + j]
                    out_pos += 1
    
    return bytes(output[:out_len])


if __name__ == '__main__':
    main()
