#!/usr/bin/env python3
"""Regenerate tileset PNG images for the editor using runtime-correct palettes.

The editor's source tileset browser (TS object) embeds base64-encoded PNGs of
each tileset.  Previous versions rendered these from the ROM's bank $17 step-
entry palette bytes, which are **encoded** (not raw RGB15).  The game engine
transforms them at runtime.  Result: wrong colours for many rooms (Starry
Shrine, boss rooms, …).

This tool fixes that by rendering from `room_palettes.json` — runtime palette
data dumped from SameBoy for all 81 rooms.

Also generates a "no-force" variant (TS_NOFRC) where BG palette colour index
1 pixels — normally forced to $6BFF (248 248 208) by the game engine every
frame — are shown in a distinctive tint so the user can identify which tile
areas will be overwritten at runtime.

Generated by: tools/regenerate_tileset_pngs.py
"""
import json, os, sys, re, base64, io, argparse

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.join(SCRIPT_DIR, '..')
ROM_PATH = os.path.join(ROOT_DIR, 'data', 'DWM-original.gbc')

sys.path.insert(0, ROOT_DIR)
from tools.decompress_tiles import decompress_lz

try:
    from PIL import Image
except ImportError:
    print("ERROR: Pillow required — pip install Pillow", file=sys.stderr)
    sys.exit(1)

# The forced colour: $6BFF = RGB(248,248,208)
FORCED_6BFF = (248, 248, 208)
# Marker colour for "no-force" view: light cyan, visually distinct from $6BFF
NOFRC_MARKER = (180, 210, 248)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def rgb15_to_rgb8(val):
    """Convert a GBC RGB15 value (uint16 LE) to an (R8, G8, B8) tuple."""
    r = (val & 0x1F) * 8
    g = ((val >> 5) & 0x1F) * 8
    b = ((val >> 10) & 0x1F) * 8
    return (r, g, b)


def parse_ts_key(ts_key):
    """Parse "bank_hex:step_decimal" → (bank, step_id)."""
    parts = ts_key.split(':')
    bank = int(parts[0], 16)
    step = int(parts[1])   # decimal
    return bank, step


def build_mapid_table(rom):
    """Build tileset_key → first mapID mapping from the $26DD table."""
    ts_to_mapid = {}
    for mapid in range(107):
        off = 0x26DD + mapid * 8
        step_id = rom[off]
        bank = rom[off + 1]
        ts_key = f"{bank:02X}:{step_id:02d}"
        if ts_key not in ts_to_mapid:
            ts_to_mapid[ts_key] = mapid
    return ts_to_mapid


def extract_tile_pal_from_html(editor_path):
    """Extract the TILE_PAL dict from the editor HTML file.

    Returns dict: ts_key → {tile_idx_str: pal_group_int, ...}
    """
    with open(editor_path) as f:
        html = f.read()
    m = re.search(r'const TILE_PAL\s*=\s*(\{.*?\});', html, re.DOTALL)
    if not m:
        raise ValueError("TILE_PAL not found in editor HTML")
    return json.loads(m.group(1))


# ---------------------------------------------------------------------------
# PNG rendering
# ---------------------------------------------------------------------------

def render_tileset_png(gfx_bytes, num_tiles, palettes, tile_pal_map,
                       force_override=None):
    """Render a 16-wide tileset PNG from 2bpp data and palette colours.

    Args:
        gfx_bytes:  raw 2bpp data (num_tiles × 16 bytes)
        num_tiles:  how many 8×8 tiles
        palettes:   list of 8 palettes, each a list of 4 (R8,G8,B8) tuples
        tile_pal_map: dict mapping str(tile_idx) → palette group number (0-7)
        force_override: if set, replace colour index 1 with this (R,G,B) tuple
                        in every palette (used for no-force marker view)

    Returns: PIL Image
    """
    cols = 16
    rows = (num_tiles + cols - 1) // cols
    img = Image.new('RGB', (cols * 8, rows * 8), (0, 0, 0))
    pixels = img.load()

    for ti in range(num_tiles):
        pal_group = tile_pal_map.get(str(ti), 0)
        if pal_group < 0 or pal_group >= len(palettes):
            pal_group = 0
        pal = list(palettes[pal_group])   # copy so override is local
        if force_override is not None:
            pal[1] = force_override

        base = ti * 16
        tx = (ti % cols) * 8
        ty = (ti // cols) * 8

        for row in range(8):
            if base + row * 2 + 1 >= len(gfx_bytes):
                continue
            lo = gfx_bytes[base + row * 2]
            hi = gfx_bytes[base + row * 2 + 1]
            for col in range(8):
                bit = 7 - col
                ci = ((hi >> bit) & 1) << 1 | ((lo >> bit) & 1)
                pixels[tx + col, ty + row] = pal[ci]

    return img


def image_to_base64(img):
    """Encode a PIL Image as a PNG base64 string."""
    buf = io.BytesIO()
    img.save(buf, format='PNG', optimize=True)
    return base64.b64encode(buf.getvalue()).decode('ascii')


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description='Regenerate editor tileset PNGs with runtime-correct palettes')
    parser.add_argument('--rom', default=ROM_PATH, help='Path to DWM-original.gbc')
    parser.add_argument('--palettes', default=None,
                        help='Path to room_palettes.json (default: auto-find)')
    parser.add_argument('--editor', default=None,
                        help='Path to editor HTML (default: auto-find)')
    parser.add_argument('--output-js', default=None,
                        help='Write JS snippet to file (default: stdout)')
    parser.add_argument('--norden-2bpp', default=None,
                        help='Path to NORDEN_tiles.2bpp')
    parser.add_argument('--norden-pal', default=None,
                        help='Path to NORDEN_palettes.json')
    parser.add_argument('--nofrc-marker', default=None,
                        help='No-force marker colour as R,G,B (default: 180,210,248)')
    args = parser.parse_args()

    # --- Load ROM ---
    with open(args.rom, 'rb') as f:
        rom = f.read()
    print(f"ROM: {len(rom)} bytes", file=sys.stderr)

    # --- Load runtime palettes ---
    pal_path = args.palettes or os.path.join(ROOT_DIR, 'extracted', 'room_palettes.json')
    with open(pal_path) as f:
        room_palettes_raw = json.load(f)
    # Convert RGB15 values → (R8,G8,B8) tuples
    room_palettes = {}
    for key, pals in room_palettes_raw.items():
        if not key.replace('_', '').replace(' ', '').split('_')[0].isdigit():
            # Skip non-numeric keys like '63_peace'
            mapid_str = key.split('_')[0]
            if not mapid_str.isdigit():
                continue
        else:
            mapid_str = key.split('_')[0] if '_' in key else key
        room_palettes[mapid_str] = [
            [rgb15_to_rgb8(c) for c in pal]
            for pal in pals
        ]
    print(f"Runtime palettes: {len(room_palettes)} rooms", file=sys.stderr)

    # --- Load TILE_PAL from editor ---
    editor_path = args.editor or os.path.join(ROOT_DIR, 'towards_editor', 'DWM1_Tile_Editor.html')
    tile_pal = extract_tile_pal_from_html(editor_path)
    print(f"TILE_PAL: {len(tile_pal)} tilesets", file=sys.stderr)

    # --- Build tileset key → mapID mapping ---
    ts_to_mapid = build_mapid_table(rom)

    # --- List all ROM tileset keys from TILE_PAL ---
    all_ts_keys = sorted(
        [k for k in tile_pal if not k.startswith('EXT:')],
        key=lambda k: (int(k.split(':')[0], 16), int(k.split(':')[1]))
    )
    ext_ts_keys = sorted([k for k in tile_pal if k.startswith('EXT:')])
    print(f"ROM tilesets: {len(all_ts_keys)}, EXT tilesets: {len(ext_ts_keys)}",
          file=sys.stderr)

    # --- No-force marker colour ---
    if args.nofrc_marker:
        nofrc = tuple(int(x) for x in args.nofrc_marker.split(','))
    else:
        nofrc = NOFRC_MARKER

    # --- Process ROM tilesets ---
    ts_runtime = {}    # ts_key → base64 (runtime palette, with forced $6BFF)
    ts_nofrc = {}      # ts_key → base64 (marker colour at index 1)

    for ts_key in all_ts_keys:
        bank, step_id = parse_ts_key(ts_key)

        # Decompress GFX
        result = decompress_lz(rom, bank, step_id)
        if result is None:
            print(f"  SKIP {ts_key}: decompress failed", file=sys.stderr)
            continue
        gfx_data, _ = result
        num_tiles = len(gfx_data) // 16

        # Find mapID for this tileset
        mapid = ts_to_mapid.get(ts_key)
        if mapid is None:
            print(f"  WARN {ts_key}: no mapID found, using Castle fallback",
                  file=sys.stderr)
            palettes = room_palettes.get('0', [[(0, 0, 0)] * 4] * 8)
        else:
            mapid_key = str(mapid)
            if mapid_key in room_palettes:
                palettes = room_palettes[mapid_key]
            else:
                # Rooms ≥80 (gate floors, mazes, arena) have dynamic palettes.
                # Fallback: use the same tileset bank's first known room, or Castle.
                fallback = None
                for alt_key, alt_mid in ts_to_mapid.items():
                    if (alt_key.startswith(ts_key.split(':')[0] + ':')
                            and str(alt_mid) in room_palettes):
                        fallback = str(alt_mid)
                        break
                if fallback:
                    palettes = room_palettes[fallback]
                    print(f"  INFO {ts_key} (mapID {mapid}): using palette from "
                          f"mapID {fallback} (same bank)", file=sys.stderr)
                else:
                    palettes = room_palettes.get('0', [[(0, 0, 0)] * 4] * 8)
                    print(f"  INFO {ts_key} (mapID {mapid}): using Castle fallback",
                          file=sys.stderr)

        tp_map = tile_pal.get(ts_key, {})

        # Runtime PNG (has $6BFF at index 1 — this IS the runtime palette)
        img_rt = render_tileset_png(gfx_data, num_tiles, palettes, tp_map)
        ts_runtime[ts_key] = image_to_base64(img_rt)

        # No-force PNG (replace index 1 with marker colour)
        img_nf = render_tileset_png(gfx_data, num_tiles, palettes, tp_map,
                                    force_override=nofrc)
        ts_nofrc[ts_key] = image_to_base64(img_nf)

        print(f"  {ts_key} → mapID {mapid}, {num_tiles} tiles", file=sys.stderr)

    # --- Process EXT tilesets ---
    for ts_key in ext_ts_keys:
        ext_name = ts_key.split(':')[1]

        # Load 2bpp data
        bpp_path = args.norden_2bpp or os.path.join(
            ROOT_DIR, 'extracted', 'custom_tilesets', f'{ext_name}_tiles.2bpp')
        if not os.path.exists(bpp_path):
            print(f"  SKIP {ts_key}: {bpp_path} not found", file=sys.stderr)
            continue
        with open(bpp_path, 'rb') as f:
            gfx_data = f.read()
        num_tiles = len(gfx_data) // 16

        # Load palette data
        pal_json_path = args.norden_pal or os.path.join(
            ROOT_DIR, 'extracted', 'custom_tilesets', f'{ext_name}_palettes.json')
        if not os.path.exists(pal_json_path):
            print(f"  SKIP {ts_key}: {pal_json_path} not found", file=sys.stderr)
            continue
        with open(pal_json_path) as f:
            pal_data = json.load(f)

        # Build per-tile palette colours from the 'tiles' structure
        # Each tile has 'colors' (4 RGB values) and 'pal_group'
        # We need to build palette arrays indexed by group
        if 'tiles' in pal_data:
            # Collect unique 4-colour sets per group
            from collections import defaultdict
            group_colors = defaultdict(list)
            for tidx_str, tinfo in pal_data['tiles'].items():
                g = tinfo.get('pal_group', 0)
                colors = [tuple(c) for c in tinfo['colors']]
                if colors not in group_colors[g]:
                    group_colors[g].append(colors)

            # Build 8 palettes — for each group, take the first colour set
            palettes = [[(0, 0, 0)] * 4] * 8
            for g, color_sets in group_colors.items():
                if g < 8:
                    palettes[g] = color_sets[0]  # representative

            # For EXT, render each tile with ITS OWN 4-colour set
            # (more accurate than using group-representative palette)
            per_tile_palettes = {}
            for tidx_str, tinfo in pal_data['tiles'].items():
                per_tile_palettes[int(tidx_str)] = [tuple(c) for c in tinfo['colors']]
        else:
            per_tile_palettes = None
            palettes = [[(0, 0, 0)] * 4] * 8

        tp_map = tile_pal.get(ts_key, {})

        # Render using per-tile palettes for accuracy
        if per_tile_palettes:
            # Custom rendering for EXT tilesets with per-tile colours
            cols = 16
            rows_count = (num_tiles + cols - 1) // cols
            img_rt = Image.new('RGB', (cols * 8, rows_count * 8), (0, 0, 0))
            img_nf = Image.new('RGB', (cols * 8, rows_count * 8), (0, 0, 0))
            px_rt = img_rt.load()
            px_nf = img_nf.load()

            for ti in range(num_tiles):
                pal_rt = list(per_tile_palettes.get(ti, [(0,0,0)]*4))
                pal_nf = list(pal_rt)  # copy
                pal_nf[1] = nofrc      # marker for index 1

                base = ti * 16
                tx = (ti % cols) * 8
                ty = (ti // cols) * 8

                for row in range(8):
                    if base + row * 2 + 1 >= len(gfx_data):
                        continue
                    lo = gfx_data[base + row * 2]
                    hi = gfx_data[base + row * 2 + 1]
                    for col in range(8):
                        bit = 7 - col
                        ci = ((hi >> bit) & 1) << 1 | ((lo >> bit) & 1)
                        px_rt[tx + col, ty + row] = pal_rt[ci]
                        px_nf[tx + col, ty + row] = pal_nf[ci]

            ts_runtime[ts_key] = image_to_base64(img_rt)
            ts_nofrc[ts_key] = image_to_base64(img_nf)
        else:
            img_rt = render_tileset_png(gfx_data, num_tiles, palettes, tp_map)
            ts_runtime[ts_key] = image_to_base64(img_rt)
            img_nf = render_tileset_png(gfx_data, num_tiles, palettes, tp_map,
                                        force_override=nofrc)
            ts_nofrc[ts_key] = image_to_base64(img_nf)

        print(f"  {ts_key} → {num_tiles} tiles (external)", file=sys.stderr)

    # --- Generate JavaScript output ---
    # Sort keys in same order as original editor
    all_keys = all_ts_keys + ext_ts_keys

    lines_rt = ['const TS = {']
    lines_nf = ['const TS_NOFRC = {']
    for ts_key in all_keys:
        if ts_key in ts_runtime:
            lines_rt.append(f'  "{ts_key}":"{ts_runtime[ts_key]}",')
            lines_nf.append(f'  "{ts_key}":"{ts_nofrc[ts_key]}",')
    lines_rt.append('};')
    lines_nf.append('};')

    js_output = '\n'.join(lines_rt) + '\n\n' + '\n'.join(lines_nf)

    if args.output_js:
        with open(args.output_js, 'w') as f:
            f.write(js_output)
        print(f"\nWritten: {args.output_js} ({len(js_output):,} bytes)", file=sys.stderr)
    else:
        print(js_output)

    # --- Summary ---
    rt_size = sum(len(v) for v in ts_runtime.values())
    nf_size = sum(len(v) for v in ts_nofrc.values())
    print(f"\n=== Summary ===", file=sys.stderr)
    print(f"Runtime PNGs:  {len(ts_runtime)} tilesets, {rt_size:,} bytes base64",
          file=sys.stderr)
    print(f"No-force PNGs: {len(ts_nofrc)} tilesets, {nf_size:,} bytes base64",
          file=sys.stderr)
    print(f"Total JS:      {len(js_output):,} bytes", file=sys.stderr)


if __name__ == '__main__':
    main()
