#!/usr/bin/env python3
"""Tile layout compiler for DWM1 custom rooms.

Standalone module for creating custom tile layouts. Designed as the
editor's layout compilation backend.

Pipeline:
  1. Accept a layout (20×16 visible tile grid, JSON or Python)
  2. Pad to 32×16 (VRAM BG map format: 12 cols of $FF padding)
  3. LZSS compress using the game's DecompressTileLayout format
  4. Output ASM db statements for bank integration
  5. Verify roundtrip decompression

The editor will call compile_layout() directly. The CLI wraps it for
standalone use and testing.

Usage:
  python3 tile_layout_compiler.py layout.json             # compile + verify
  python3 tile_layout_compiler.py layout.json -o out.asm  # emit ASM include
  python3 tile_layout_compiler.py --dump-rom 0x30 13      # dump ROM layout as JSON template

Generated by: tools/tile_layout_compiler.py
"""
import json, os, sys, argparse

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(SCRIPT_DIR, '..'))

from tools.compress_tiles import compress_lz


# ---------------------------------------------------------------------------
# Core API (editor calls these)
# ---------------------------------------------------------------------------

def pad_layout(visible_20x16):
    """Pad a 20-column visible layout to 32-column VRAM format.

    Args:
        visible_20x16: list of 16 rows, each a list of 20 tile indices (0x00-0xFF)

    Returns:
        bytes: 512 bytes (32×16) ready for LZSS compression
    """
    if len(visible_20x16) != 16:
        raise ValueError(f"Layout must have 16 rows, got {len(visible_20x16)}")

    output = bytearray(512)
    for row in range(16):
        row_data = visible_20x16[row]
        if len(row_data) != 20:
            raise ValueError(f"Row {row} must have 20 columns, got {len(row_data)}")
        for col in range(20):
            output[row * 32 + col] = row_data[col]
        # Padding columns 20-31: $FF (matches all vanilla layouts)
        for col in range(20, 32):
            output[row * 32 + col] = 0xFF

    return bytes(output)


def compile_layout(visible_20x16):
    """Compile a 20×16 visible layout to LZSS compressed data.

    Args:
        visible_20x16: list of 16 rows, each a list of 20 tile indices

    Returns:
        bytes: LZSS compressed data (header + body), ready to embed in a bank
    """
    padded = pad_layout(visible_20x16)
    return compress_lz(padded)


def verify_roundtrip(visible_20x16, compressed=None):
    """Verify that compress→decompress recovers the original layout.

    Returns:
        (ok: bool, message: str)
    """
    padded = pad_layout(visible_20x16)
    if compressed is None:
        compressed = compress_lz(padded)

    # Decompress
    out_len = compressed[0] | (compressed[1] << 8)
    marker = compressed[2]
    src = 3

    output = bytearray(out_len)
    out_pos = 0

    while out_pos < out_len and src < len(compressed):
        b = compressed[src]; src += 1
        if b != marker:
            output[out_pos] = b
            out_pos += 1
        else:
            offset_low = compressed[src]; src += 1
            control = compressed[src]; src += 1
            copy_len = (control & 0x0F) + 4
            if copy_len == 0x13:
                copy_len = compressed[src] + 0x13; src += 1
            offset_high = (control >> 4) & 0x0F
            back_offset = (offset_high << 8) | offset_low
            for i in range(copy_len):
                if out_pos >= out_len:
                    break
                ref = back_offset + i
                output[out_pos] = output[ref] if ref < out_len else 0
                out_pos += 1

    if bytes(output) == padded:
        return True, f"Roundtrip OK: {len(padded)} → {len(compressed)} → {len(padded)} bytes"
    else:
        for i in range(min(len(output), len(padded))):
            if output[i] != padded[i]:
                return False, f"Mismatch at byte {i}: got ${output[i]:02X} expected ${padded[i]:02X}"
        return False, f"Length mismatch: got {len(output)} expected {len(padded)}"


def to_asm_db(compressed, label="CustomLayout_0"):
    """Format compressed data as RGBDS db statements.

    Args:
        compressed: bytes from compile_layout()
        label: ASM label name

    Returns:
        str: ASM source text with db statements
    """
    lines = [f"{label}:"]
    # Emit in rows of 16 bytes
    for i in range(0, len(compressed), 16):
        chunk = compressed[i:i+16]
        hex_vals = ", ".join(f"${b:02X}" for b in chunk)
        lines.append(f"    db {hex_vals}")
    return "\n".join(lines)


def to_asm_bank(layouts, bank_number):
    """Generate a complete bank ASM file with pointer table and layouts.

    Args:
        layouts: list of (label, compressed_bytes) tuples
        bank_number: ROM bank number (e.g. 0x64)

    Returns:
        str: complete ASM source for the bank
    """
    lines = [
        f"; =============================================================================",
        f"; BANK ${bank_number:02X} — Custom Tile Layout Data",
        f"; =============================================================================",
        f"; Generated by tools/tile_layout_compiler.py",
        f"; Format: pointer table at $4001, LZSS compressed layouts",
        f"; Each layout decompresses to 512 bytes (32×16 tile grid)",
        f"; Engine reads via DecompressTileLayout ($1627): D=bank, E=entry index",
        f"; =============================================================================",
        f"",
        f'SECTION "ROM Bank ${bank_number:03X}", ROMX[$4000], BANK[${bank_number:02X}]',
        f"    db ${bank_number:02X}  ; bank self-ID",
        f"",
        f"; Pointer table at $4001 — indexed by step_entry byte 0 (step_id)",
    ]

    # Pointer table
    for label, _ in layouts:
        lines.append(f"    dw {label}")

    lines.append("")

    # Layout data
    for label, compressed in layouts:
        lines.append(f"; {label}: {len(compressed)} bytes compressed (512 decompressed)")
        lines.append(to_asm_db(compressed, label))
        lines.append("")

    # Pad rest of bank with nops to fill 16KB
    lines.append("; Remaining bank space available for additional layouts")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# ROM layout dumper (extract existing layouts as JSON templates)
# ---------------------------------------------------------------------------

def dump_rom_layout(rom_path, bank, step_id):
    """Extract and dump a layout from the ROM as a 20×16 JSON grid."""
    from tools.decompress_tiles import decompress_lz

    with open(rom_path, 'rb') as f:
        rom = f.read()

    result = decompress_lz(rom, bank, step_id)
    if not result:
        return None

    data, addr = result
    # Extract 20 visible columns from the 32-column grid
    grid = []
    for row in range(16):
        row_data = []
        for col in range(20):
            row_data.append(data[row * 32 + col])
        grid.append(row_data)

    return grid


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def print_layout(grid, label="Layout"):
    """Pretty-print a 20×16 tile grid."""
    print(f"\n{label} (20×16 visible grid):")
    for row in range(16):
        cols = " ".join(f"{grid[row][col]:02X}" for col in range(20))
        print(f"  R{row:2d}: {cols}")


def main():
    parser = argparse.ArgumentParser(description="DWM1 Tile Layout Compiler")
    parser.add_argument("layout_json", nargs="?", help="JSON file with 20×16 tile grid")
    parser.add_argument("-o", "--output", help="Output ASM file")
    parser.add_argument("--bank", type=lambda x: int(x, 0), default=0x64,
                        help="Bank number for ASM output (default: 0x64)")
    parser.add_argument("--label", default="CustomLayout_0",
                        help="ASM label for the layout")
    parser.add_argument("--dump-rom", nargs=2, metavar=("BANK", "STEP_ID"),
                        help="Dump ROM layout as JSON (e.g., --dump-rom 0x30 13)")
    parser.add_argument("--preview", action="store_true",
                        help="Print layout grid to stdout")
    parser.add_argument("--verify-only", action="store_true",
                        help="Only verify roundtrip, don't output")
    args = parser.parse_args()

    rom_path = os.path.join(SCRIPT_DIR, '..', 'data', 'DWM-original.gbc')

    if args.dump_rom:
        bank = int(args.dump_rom[0], 0)
        step_id = int(args.dump_rom[1], 0)
        grid = dump_rom_layout(rom_path, bank, step_id)
        if grid is None:
            print(f"Failed to decompress bank ${bank:02X} entry {step_id}")
            sys.exit(1)
        print(json.dumps(grid, indent=2))
        return

    if not args.layout_json:
        parser.print_help()
        sys.exit(1)

    # Load layout
    with open(args.layout_json) as f:
        grid = json.load(f)

    if args.preview:
        print_layout(grid, os.path.basename(args.layout_json))

    # Compile
    compressed = compile_layout(grid)
    print(f"Compressed: {len(compressed)} bytes (from 512, ratio {len(compressed)/512:.2f})")

    # Verify roundtrip
    ok, msg = verify_roundtrip(grid, compressed)
    print(f"{'✓' if ok else '✗'} {msg}")
    if not ok:
        sys.exit(1)

    if args.verify_only:
        return

    # Output
    if args.output:
        asm = to_asm_bank([(args.label, compressed)], args.bank)
        with open(args.output, 'w') as f:
            f.write(asm + "\n")
        print(f"Wrote {args.output}")
    else:
        # Print ASM to stdout
        print()
        print(to_asm_db(compressed, args.label))


if __name__ == '__main__':
    main()
